import type { Metadata } from "next";
import Link from "next/link";
import { FileCheck2, ShieldCheck, Sparkles } from "lucide-react";
import { CvSummaryGenerator } from "@/components/cv-summary-generator";
import { FaqSection, SectionLabel } from "@/components/marketing";
import { site } from "@/lib/site";

const path = "/tools/cv-summary-generator-uk";
export const metadata: Metadata = { title: "Free CV Summary Generator UK - No Signup", description: "Generate three concise UK CV summary options from your real experience, skills and target role. Free, editable and no signup required.", alternates: { canonical: path }, openGraph: { title: "Free UK CV Summary Generator", description: "Create three evidence-led, editable summaries for the top of your UK CV.", url: path } };
const faqs = [
  { question: "Is a CV summary the same as a personal statement?", answer: "On a UK CV, CV summary, personal profile, personal summary and CV personal statement usually describe the same concise section at the top of the document. This is different from a longer university or application-form personal statement." },
  { question: "How long should a UK CV summary be?", answer: "Prospects advises keeping a CV personal profile below 150 words. This generator produces shorter 40-to-100-word options designed to be scanned quickly and edited around your strongest evidence." },
  { question: "What should a CV summary include?", answer: "State your relevant professional or educational identity, support it with specific skills or achievements, and make your intended direction clear. Remove generic claims that are not evidenced elsewhere in the CV." },
  { question: "Does this generator invent experience?", answer: "It is instructed to use only supplied facts, and generated numbers are checked against your inputs. AI can still make mistakes, so verify every statement before applying." },
  { question: "Is the CV summary generator free?", answer: "Yes. A limited number of generations are available without an account, payment details or subscription." },
];
const schemas = [{ "@context": "https://schema.org", "@type": "WebApplication", name: "WorkCV UK CV Summary Generator", applicationCategory: "BusinessApplication", operatingSystem: "Any", url: `${site.url}${path}`, offers: { "@type": "Offer", price: "0", priceCurrency: "GBP" } }, { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map((item) => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } })) }];

export default function Page() {
  return <>{schemas.map((schema, index) => <script key={index} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />)}
    <section className="quiet-grid border-b border-line bg-paper py-14 md:py-20"><div className="container-page"><div className="max-w-4xl"><p className="mb-4 text-sm font-bold uppercase tracking-[0.14em] text-navy">Free UK CV writing tool</p><h1 className="font-display text-4xl font-semibold leading-[1.06] text-navy md:text-6xl">Free CV summary generator.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-muted">Turn your background, strongest evidence and target role into three concise options for the top of your UK CV. Compare the angles, edit your preferred version and keep every claim truthful.</p><div className="mt-6 flex flex-wrap gap-x-6 gap-y-3 text-sm font-bold text-navy"><span className="flex items-center gap-2"><Sparkles className="h-5 w-5 text-gold" />Three distinct drafts</span><span className="flex items-center gap-2"><FileCheck2 className="h-5 w-5 text-success" />Evidence checked</span><span className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-[#63788c]" />No signup</span></div></div><div className="mt-10 rounded-lg border border-line-strong bg-surface p-5 shadow-soft md:p-7"><CvSummaryGenerator /></div></div></section>
    <section className="bg-surface py-20"><div className="container-page grid gap-12 lg:grid-cols-[0.85fr_1.15fr]"><div><SectionLabel>Three useful angles</SectionLabel><h2 className="font-display text-4xl font-semibold text-navy md:text-5xl">Choose emphasis, not invented personality.</h2><p className="mt-6 text-base leading-8 text-muted">Generic generators produce one polished paragraph and hide the trade-offs. WorkCV gives you a balanced version, an achievement-led version and a shorter option, all constrained to your evidence.</p></div><div className="divide-y divide-line border-y border-line">{[["Balanced","Connect professional identity, relevant evidence and direction."],["Achievement-led","Open with the strongest supplied outcome when one exists."],["Concise","Keep the essential fit while using the least space."]].map(([title, body], index) => <article key={title} className="grid gap-4 py-6 sm:grid-cols-[44px_1fr]"><span className="inline-flex h-10 w-10 items-center justify-center rounded-md bg-paper text-sm font-bold text-navy">{index + 1}</span><div><h3 className="font-display text-2xl font-semibold text-navy">{title}</h3><p className="mt-2 text-sm leading-7 text-muted">{body}</p></div></article>)}</div></div></section>
    <section className="border-y border-line bg-paper py-20"><div className="container-page grid gap-10 lg:grid-cols-[1fr_0.8fr]"><div><SectionLabel>UK terminology</SectionLabel><h2 className="font-display text-4xl font-semibold text-navy md:text-5xl">One section, several common names.</h2><p className="mt-6 text-base leading-8 text-muted">Prospects describes a CV personal statement as a concise paragraph or summary and notes that it is also called a personal profile, personal summary or executive summary. WorkCV uses one canonical tool so those labels do not create duplicate pages.</p><p className="mt-4 text-sm font-bold text-navy">Research reviewed 10 July 2026.</p></div><div className="grid content-start gap-3 text-sm font-bold text-navy"><a href="https://www.prospects.ac.uk/careers-advice/cvs-and-cover-letters/writing-a-personal-statement-for-your-cv/" target="_blank" rel="noreferrer" className="rounded-md border border-line bg-white p-4 hover:border-navy">Prospects: writing a personal statement for your CV</a><a href="https://nationalcareers.service.gov.uk/careers-advice/cv-sections" target="_blank" rel="noreferrer" className="rounded-md border border-line bg-white p-4 hover:border-navy">National Careers Service: CV introduction</a></div></div></section>
    <section className="bg-surface py-16"><div className="container-page"><h2 className="font-display text-3xl font-semibold text-navy">Continue building your CV.</h2><div className="mt-6 flex flex-wrap gap-3 text-sm font-bold text-navy"><Link href="/tools/cv-bullet-point-generator" className="rounded-md border border-line-strong bg-white px-4 py-3 hover:border-navy">Generate experience bullets</Link><Link href="/tools/ats-score-checker" className="rounded-md border border-line-strong bg-white px-4 py-3 hover:border-navy">Check vacancy relevance</Link><Link href="/tools" className="rounded-md border border-line-strong bg-white px-4 py-3 hover:border-navy">See all free tools</Link></div></div></section>
    <FaqSection faqs={faqs} title="UK CV summary questions." />
  </>;
}
