import type { Metadata } from "next";

import { AdviceCard, BulletList, CopyTemplate, EditorialGuideShell, GuideSection } from "@/components/editorial-guide-shell";

const path = "/career-advancement-strategies-uk";
export const metadata: Metadata = { title: "Career Progression Plan UK: 30-60-90 Day Guide", description: "Build a practical career progression plan with a target-role gap analysis, evidence log, manager conversation script and 30-60-90 day actions.", alternates: { canonical: path }, openGraph: { title: "Career Progression Plan: A Practical UK Guide", description: "Move from a vague promotion goal to evidence, conversations and measurable next steps.", url: path } };

const faqs = [
  { question: "How do I make a career progression plan?", answer: "Define a specific target role or responsibility, compare its expectations with your current evidence, choose one or two gaps to close and set dated actions. Review the plan regularly instead of treating it as a one-off document." },
  { question: "How do I ask my manager about progression?", answer: "Ask for a dedicated conversation, explain the direction you want to explore, show evidence of your current contribution and request clarity on the skills, scope and results expected at the next level. Agree actions and a review date." },
  { question: "Should I wait for a promotion or apply elsewhere?", answer: "Test both paths against evidence: whether a role exists, whether expectations are clear, whether you can gain the missing scope and whether there is a credible timeline. Quietly keeping your CV current gives you options without forcing an immediate decision." },
  { question: "What should I put on my CV for a promotion?", answer: "Show increased scope, ownership, judgement and outcomes—not merely longer service. Compare your evidence with the target role and make your individual contribution clear without inflating your title." },
];

export default function CareerAdvancementPage() {
  return <EditorialGuideShell path={path} eyebrow="Career progression UK" title="Career advancement strategies: turn “I want to progress” into a 90-day plan." intro="Progression is easier to act on when you define the next level, collect evidence of what you already do, identify the real gaps and have a specific conversation. This guide gives you the worksheets and wording to do that." answer="Choose one target—more scope, a promotion, higher pay, a specialist path or a move elsewhere. Collect three to five target-role descriptions, build a skills-and-evidence gap table, agree one stretch opportunity and one development action, then review progress after 30, 60 and 90 days." reviewed="13 September 2026" faqs={faqs} ctaHeading="Make your progression visible in the CV—not just in your head." ctaBody="Turn stronger scope and achievements into a clear UK CV, preview it free and pay once only if you download the PDF. No subscription and no automatic renewal." trackingContext="career_progression_editorial" relatedLinks={[["CV bullet point generator", "/tools/cv-bullet-point-generator"], ["Transferable skills translator", "/tools/transferable-skills-translator-uk"], ["Top UK job boards", "/top-job-boards-uk"], ["Career-change CV guide", "/career-change-cv-uk"], ["No-subscription CV builder", "/cv-builder-no-subscription-uk"]]}>
    <GuideSection label="Pick the actual goal" title="Career progression is not always a promotion."><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4"><AdviceCard title="More responsibility"><p>You want broader decisions, projects, people or budgets—possibly before a title changes.</p></AdviceCard><AdviceCard title="Promotion"><p>You want the defined next level and need clarity on scope, evidence, process and timing.</p></AdviceCard><AdviceCard title="Specialist growth"><p>You want deeper expertise, influence or pay without moving into people management.</p></AdviceCard><AdviceCard title="External move"><p>The next step may exist elsewhere when your current organisation has no role, scope or credible path.</p></AdviceCard></div></GuideSection>

    <GuideSection label="Target-role gap analysis" title="Compare evidence, not confidence." tone="paper" intro="Collect three to five recent descriptions for the level you want. Repeated expectations are a stronger signal than one unusual advert.">
      <div className="overflow-x-auto rounded-lg border border-line bg-white"><table className="w-full min-w-[780px] text-left text-sm"><thead className="bg-navy text-white"><tr><th className="p-4">Target expectation</th><th className="p-4">Evidence I have</th><th className="p-4">Gap</th><th className="p-4">Next action</th><th className="p-4">Proof / date</th></tr></thead><tbody>
        <tr className="border-t border-line align-top"><td className="p-4">Lead work across teams</td><td className="p-4">Coordinated weekly handover with Operations</td><td className="p-4">No end-to-end cross-team project</td><td className="p-4">Propose ownership of the Q4 reporting improvement</td><td className="p-4">Scope agreed by 30 Sep; review in December</td></tr>
        <tr className="border-t border-line text-muted"><td className="p-4">[Repeated expectation]</td><td className="p-4">[Specific example]</td><td className="p-4">[Missing scope or skill]</td><td className="p-4">[Work, learning or exposure]</td><td className="p-4">[Observable result and date]</td></tr>
        <tr className="border-t border-line text-muted"><td className="p-4">[Repeated expectation]</td><td className="p-4">[Specific example]</td><td className="p-4">[Missing scope or skill]</td><td className="p-4">[Work, learning or exposure]</td><td className="p-4">[Observable result and date]</td></tr>
      </tbody></table></div>
    </GuideSection>

    <GuideSection label="Build evidence continuously" title="Keep an achievement log before you need the CV."><div className="grid gap-5 md:grid-cols-2"><AdviceCard title="Record each month"><BulletList items={["The problem, risk or opportunity—not just the task.", "Your responsibility and the decisions you personally made.", "Who you worked with and the level of stakeholder involved.", "The result: time, quality, revenue, cost, safety, service or learning.", "A link, message, review or metric that can help you verify it later."]} /></AdviceCard><AdviceCard title="Turn activity into evidence"><p><strong className="text-navy">Activity:</strong> “Helped with weekly reports.”</p><p><strong className="text-navy">Evidence:</strong> “Took ownership of the weekly service report, reconciled inputs from three teams and introduced an exception check that reduced last-minute corrections.”</p><p>The stronger version explains ownership, complexity and change. Only add a measured result when you can verify it.</p></AdviceCard></div></GuideSection>

    <GuideSection label="The manager conversation" title="Ask for expectations and opportunities, not a vague promise." tone="paper"><CopyTemplate title="Conversation opener">{`I’d like to have a focused conversation about my development and the next level of responsibility. I’m interested in moving towards [target role / scope].

I believe I already demonstrate [two relevant expectations], for example [brief evidence]. From the role descriptions and feedback I’ve reviewed, I need stronger evidence in [one or two gaps].

Could we discuss what good performance at the next level looks like here, which gaps you see, and whether there is a project or responsibility I could own to demonstrate that? I’d also like to agree what we can review by [date].`}</CopyTemplate>
      <div className="mt-6 grid gap-5 md:grid-cols-2"><AdviceCard title="Questions that create clarity"><BulletList items={["What scope or outcomes distinguish the next level from my current role?", "Which evidence do you think I already demonstrate?", "What are the two most important gaps you see?", "What work could let me demonstrate those expectations?", "How is promotion decided, who is involved and when are decisions made?", "Can we record the actions and review them on a specific date?"]} /></AdviceCard><AdviceCard title="Listen for the quality of the answer"><p>A useful answer names expectations, evidence, an opportunity and a review point. “Keep doing what you’re doing” is praise, not a progression plan. Ask what observable change would make the answer different at the next review.</p><p>A manager cannot guarantee a vacancy or promotion, but they should be able to discuss development and provide honest feedback.</p></AdviceCard></div>
    </GuideSection>

    <GuideSection label="Your 30-60-90 day plan" title="Small enough to execute, concrete enough to review."><div className="grid gap-5 md:grid-cols-3"><AdviceCard title="Days 1–30: define"><BulletList items={["Choose the target and collect role descriptions.", "Complete the gap table with evidence.", "Ask for feedback from your manager and one trusted colleague.", "Agree one work-based opportunity and one learning action."]} /></AdviceCard><AdviceCard title="Days 31–60: demonstrate"><BulletList items={["Take visible ownership of the agreed work.", "Request specific feedback while you can still adjust.", "Build the missing skill through real application, not course completion alone.", "Record decisions, stakeholders and emerging results."]} /></AdviceCard><AdviceCard title="Days 61–90: review"><BulletList items={["Compare results with the agreed expectations.", "Update the evidence log and CV bullets.", "Ask what remains before the next-level decision.", "Decide whether the internal path is credible or an external search should begin."]} /></AdviceCard></div></GuideSection>

    <GuideSection label="Internal or external?" title="Use signals, not one disappointing week." tone="paper"><div className="grid gap-5 md:grid-cols-2"><AdviceCard title="An internal path may be credible when"><BulletList items={["The next role or level is defined and examples exist.", "Decision-makers give consistent expectations.", "You can access work that demonstrates the missing scope.", "Feedback is specific and changes as your evidence changes.", "There is a process or realistic review window."]} /></AdviceCard><AdviceCard title="Test the external market when"><BulletList items={["The role does not exist or no one can explain the criteria.", "The goalposts move after agreed evidence is delivered.", "You cannot gain the necessary responsibility where you are.", "Pay or scope remains materially below comparable roles.", "You want a different field, environment or type of work."]} /></AdviceCard></div></GuideSection>

    <GuideSection label="Trusted starting points" title="Use free guidance before buying another course."><p className="max-w-4xl text-sm leading-7 text-muted">The <a className="font-bold text-navy underline" href="https://nationalcareers.service.gov.uk/careers-advice/identifying-skills-and-upskilling">National Careers Service skills guide</a> recommends identifying existing and missing skills, setting specific and time-bound goals, and keeping the CV updated. The government’s <a className="font-bold text-navy underline" href="https://jobhelp.campaign.gov.uk/tips-on-how-to-improve-your-career-prospects/">JobHelp progression guidance</a> also suggests an open manager conversation while recognising that sometimes progression requires a new employer. Those principles shaped the worksheets above.</p></GuideSection>
  </EditorialGuideShell>;
}
