import Link from "next/link";
import { Guide, GuideSection, GuideTable, CvTextExample, GuideSource, guideMetadata } from "@/components/cv-guide";
import { EvidenceSelector } from "@/components/career-worksheets";
import { FaqSection } from "@/components/marketing";
import { PassOffer } from "@/components/pass-offer";
import { jobPassExamples as ex } from "@/lib/job-pass-examples";
const path="/overqualified-cv-example-uk";
export const metadata=guideMetadata(path,"Overqualified CV & Cover Letter Examples UK","See how the same candidate applies for a manager and a coordinator role. Compare complete UK CVs and letters, then choose evidence relevant to your vacancy.");
const faqs=[
{question:"Should I simplify my CV if I am overqualified?",answer:"Make the relevant work easier to find. Reduce less relevant detail while keeping your history accurate. More senior experience does not automatically prove every skill in a different job."},
{question:"Can I change my job title to look less senior?",answer:"Keep the actual historical title. Add an accurate functional clarification if helpful. A target-role heading can describe the job you want; it must not replace the titles of jobs you held."},
{question:"Should I remove a degree?",answer:"There is no automatic rule to hide qualifications. Keep relevant qualifications and follow the application's instructions. Answer forms requesting full qualifications accurately."},
{question:"How do I explain wanting a less senior role?",answer:"Give a genuine reason connected to the work. For example, a candidate who actually wants hands-on coordination can explain that preference. Do not invent family circumstances or promise permanent commitment."},
{question:"Must I mention salary in my cover letter?",answer:"Not by default. Follow the employer's instructions and consider the advertised scope and pay. Do not claim you accept a salary unless you have decided that is true."},
{question:"What if I am changing sector?",answer:"Show relevant transferable evidence and recognise any missing sector skills. A senior title in one sector does not establish expertise in another."},
{question:"Should I use the word overqualified in my letter?",answer:"You usually have a more useful message: why you want this role and the evidence that fits it. Avoid apologising for your experience or diagnosing how an employer will judge you."},
{question:"How do I keep versions consistent?",answer:"Keep an original fact bank with actual employers, dates, titles and qualifications. Change emphasis and wording for the vacancy, then check every version against that source."}];
export default function Page(){return <Guide path={path} title="Applying for a less senior role? CV and cover letter examples" intro="Lead with the experience relevant to this vacancy, keep your actual job titles and dates, and explain your genuine reason for wanting the work. These two complete applications show the same candidate at different responsibility levels." reviewed="2026-10-05" published="2026-10-05" placement="overqualified_guide" action={["Start my own CV","/editor?template=classic&new=1"]} links={[["Career-change CV examples","/career-change-cv-uk"],["CV after long service","/cv-after-long-service-uk"],["Tailor a CV to a vacancy","/tailor-cv-to-job-description-uk"],["Return-to-work CV","/return-to-work-cv-uk"]]}>
 <nav aria-label="On this page" className="flex flex-wrap gap-4 text-sm font-bold underline"><a href="#manager">Manager application</a><a href="#coordinator">Coordinator application</a><a href="#evidence">Choose your evidence</a><a href="#questions">Questions</a></nav>
 <GuideSection title="Experience is useful when it matches the work"><p>A rejection does not establish that you were considered overqualified. Employers may have other reasons, and a more senior job title does not prove every requirement. Focus on what you can do and why you want the specific responsibilities.</p><p>Alex Reed is a fictional Office Manager exploring both manager and coordinator roles. For the coordinator application, Alex has explicitly said: “I want to focus on hands-on coordination rather than supervising staff.” No salary acceptance, personal circumstance or promise of long-term tenure has been supplied.</p><GuideSource href="https://www.hays.com.au/career-advice/job-hunting/how-to-apply-for-a-role-you-are-overqualified-for">Hays Australia: qualitative guidance on motivation and relevant experience</GuideSource></GuideSection>
 <GuideSection id="manager" title="Application one: office manager"><CvTextExample title="Fictional office manager advert" text={ex.managerAdvert}/><CvTextExample title="Complete manager CV" text={ex.managerCv}/><CvTextExample title="Matching manager cover letter" text={ex.managerLetter}/></GuideSection>
 <GuideSection id="coordinator" title="Application two: office coordinator"><CvTextExample title="Fictional coordinator advert" text={ex.coordinatorAdvert}/><CvTextExample title="Complete coordinator CV" text={ex.coordinatorCv}/><CvTextExample title="Matching coordinator cover letter" text={ex.coordinatorLetter}/></GuideSection>
 <GuideSection title="What changed — and which facts stayed the same"><GuideTable caption="Two applications from Alex's same fact bank" headings={["Element","Manager version","Coordinator version"]} rows={[["Target heading","Office Manager","Office Coordinator — desired role, not a past title"],["Profile","Coordination and supervision","Hands-on focus and genuine motivation"],["First bullets","Supervision of two assistants","Meeting rooms, inductions, supplier records"],["Actual past title","Office Manager","Office Manager — unchanged"],["Management scope","Prominent","Briefly retained, not denied"],["Education and dates","Original degree and dates","Exactly the same"],["Letter","Management responsibilities","Why this coordination role fits Alex's choice"]]}/><p>No version claims payroll ownership, advanced finance qualifications or a cost saving. Invoice filing is not payroll experience. The degree is retained in both examples.</p></GuideSection>
 <GuideSection title="Keep, summarise or leave in your master notes"><GuideTable caption="Evidence decisions for the coordinator vacancy" headings={["Evidence","Decision","Reason"]} rows={[["Meeting-room bookings","Lead with it","Directly relevant to the vacancy"],["Supplier records and queries","Lead with it","Matches day-to-day duties"],["Inductions","Include","Supports new-starter arrangements"],["Monthly expense spreadsheet","Include briefly","Shows practical spreadsheet use"],["Supervision of two assistants","Summarise","Honest context, not the coordinator's main duty"],["Payroll","Do not claim","Not supplied in Alex's evidence"]]}/><p>Keep official titles. A truthful clarification can sit beside a title; it must not hide the real job. Avoid blanket advice to remove a degree, lower your salary expectations or disclose health and family circumstances. Where an application form requests full history or qualifications, answer accurately.</p><GuideSource href="https://nationalcareers.service.gov.uk/careers-advice/covering-letter">National Careers Service: role-specific letters supported by facts</GuideSource></GuideSection>
 <GuideSection id="evidence" title="Choose evidence for this job"><p>Paste the requirements, add your own facts and decide what belongs in this version. The worksheet keeps original notes separate from your selected wording. It does not diagnose overqualification or judge employability.</p><EvidenceSelector/></GuideSection>
 <GuideSection title="Explain the choice in an interview"><CvTextExample title="An answer using Alex's stated motivation" text="I am choosing a role where I can focus on the practical coordination work I enjoy. My previous position included staff supervision, but the bookings, supplier queries and office records in this role are the responsibilities I want to concentrate on."/><p>This explains a genuine preference; it does not guarantee that an employer's concerns disappear. If asked about salary, availability or future plans, answer from your own decisions rather than use a prewritten promise.</p><p>Ready to prepare a specific application? Use the <Link href="/tools/job-application-pack-uk" className="font-bold underline">CV and letter tailoring tool</Link>. For a sector change, see the <Link href="/career-change-cv-uk" className="underline">career-change examples</Link>.</p></GuideSection>
 <PassOffer audience="tailoring" trackingLabel="overqualified_pass_example"/>
 <div id="questions"><FaqSection title="Overqualified CV and cover-letter questions" faqs={faqs}/></div>
 </Guide>;}
