import test from 'node:test';
import assert from 'node:assert/strict';
import {isAnalyticsAdminEmail,parseAnalyticsRange,parseAnalyticsView} from '../lib/admin-access.ts';
import {isPublicMeasurementPath} from '../lib/public-paths.ts';
import {collectAdminAnalytics} from '../lib/admin-analytics-query.ts';
test('admin access denies by default and matches exact emails',()=>{assert.equal(isAnalyticsAdminEmail('admin@example.com',''),false);assert.equal(isAnalyticsAdminEmail('Admin@example.com',' admin@example.com '),true);assert.equal(isAnalyticsAdminEmail('admin@example.com.attacker.com','admin@example.com'),false);});
test('safe parameters and private measurement exclusion',()=>{assert.equal(parseAnalyticsRange(['24h']),'7d');assert.equal(parseAnalyticsView('invalid'),'overview');assert.equal(isPublicMeasurementPath('/admin/analytics?range=7d'),false);});
test('query failure rolls back read-only report',async()=>{const calls:string[]=[];await assert.rejects(collectAdminAnalytics({query:async sql=>{calls.push(sql);if(sql==='SELECT NOW() AS at')throw Error('unavailable');return {rows:[]};}},{range:'7d',excludedUsers:[],passProductId:'pass',cvProductId:'cv',ingestEnabled:true}));assert.match(calls[0],/READ ONLY/);assert.equal(calls.at(-1),'ROLLBACK');});
test('real PostgreSQL report totals and privacy',{skip:!process.env.ADMIN_ANALYTICS_TEST_DATABASE_URL},async()=>{const {seedAnalyticsFixture}=await import('../scripts/admin-analytics-fixture.ts');const pool=await seedAnalyticsFixture();const client=await pool.connect();try{for(const range of ['24h','7d','30d'] as const){const r=await collectAdminAnalytics(client,{range,excludedUsers:['admin@example.invalid'],passProductId:'pdt_0NoafhI03VVtoLtkpGLHe',cvProductId:'pdt_0NgvxNXDilMTh3bpfLPq2',ingestEnabled:true});assert.equal(r.summary.visitors,3);assert.equal(r.summary.paid_orders,2);assert.equal(r.summary.pass_orders,1);assert.equal(Number(r.summary.gbp_gross_minor),2499);assert.equal(r.cohort[0].buyer_visitors,1);assert.equal(r.cohort[0].extra_browser_visitors,1);assert.equal(r.quality.excluded_orders,2);assert.equal(r.quality.zero_value_orders,1);assert.ok(r.sourceSales.some(x=>x.source==='careercloud'&&x.campaign==='uk_cv_guide'));assert.ok(r.plans.some(x=>x.currency==='USD'&&x.refund_flags===1));assert.doesNotMatch(JSON.stringify(r),/DO_NOT_INCLUDE|admin@example.invalid|buyer@example.invalid|\/admin\/analytics/);}}finally{client.release();await pool.end();}});
