import type { Metadata } from "next";
import Link from "next/link";
import { Download, FileText, PenLine, ShieldCheck } from "lucide-react";
import { CoverLetterTemplate } from "@/components/cover-letter-template";
import { FaqSection, SectionLabel } from "@/components/marketing";
import { site } from "@/lib/site";

const path = "/tools/cover-letter-template-uk";
export const metadata: Metadata = { title: "Free UK Cover Letter Template - Word Download", description: "Use a free editable UK cover letter template or download it for Microsoft Word. Correct UK structure and sign-off, no signup required.", alternates: { canonical: path }, openGraph: { title: "Free UK Cover Letter Template", description: "Edit, copy or download a structured UK cover letter template with practical prompts.", url: path } };
const faqs = [
  { question: "Is this UK cover letter template free?", answer: "Yes. You can edit and copy the template in your browser or download the Word document without an account, email gate, payment or subscription." },
  { question: "How should a UK cover letter be structured?", answer: "Use a direct opening naming the role, one or two evidence paragraphs connecting your experience to the vacancy, and a concise closing. The National Careers Service describes a typical cover letter as three to five paragraphs." },
  { question: "Should I use Yours sincerely or Yours faithfully?", answer: "Use Yours sincerely when you address a named person. Use Yours faithfully after Dear Sir or Madam when you do not know the recipient's name." },
  { question: "Can I reuse the same cover letter?", answer: "Keep the overall structure, but tailor the role, employer, motivation and evidence for every application. Avoid sending unchanged generic paragraphs." },
  { question: "Should I copy the placeholder wording exactly?", answer: "No. Replace every bracketed prompt with truthful details from your experience and delete the brackets. The prompts provide structure rather than finished application text." },
];
const schemas = [{ "@context": "https://schema.org", "@type": "SoftwareApplication", name: "WorkCV UK Cover Letter Template", applicationCategory: "BusinessApplication", operatingSystem: "Any", url: `${site.url}${path}`, offers: { "@type": "Offer", price: "0", priceCurrency: "GBP" } }, { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map((item) => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } })) }];

export default function Page() { return <>{schemas.map((schema, index) => <script key={index} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />)}
  <section className="quiet-grid border-b border-line bg-paper py-14 md:py-20"><div className="container-page"><div className="max-w-4xl"><p className="mb-4 text-sm font-bold uppercase tracking-[0.14em] text-navy">Edit, copy or download</p><h1 className="font-display text-4xl font-semibold leading-[1.06] text-navy md:text-6xl">Free UK cover letter template.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-muted">Use a four-paragraph structure with prompts for your real motivation and evidence. Choose the correct UK sign-off, edit the text directly or download a Word copy.</p><div className="mt-6 flex flex-wrap gap-x-6 gap-y-3 text-sm font-bold text-navy"><span className="flex items-center gap-2"><PenLine className="h-5 w-5 text-gold" />Editable in browser</span><span className="flex items-center gap-2"><Download className="h-5 w-5 text-success" />Word download</span><span className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-[#63788c]" />No signup</span></div></div><div className="mt-10 rounded-lg border border-line-strong bg-surface p-5 shadow-soft md:p-7"><CoverLetterTemplate /></div></div></section>
  <section className="bg-surface py-20"><div className="container-page grid gap-12 lg:grid-cols-[0.85fr_1.15fr]"><div><SectionLabel>Four focused paragraphs</SectionLabel><h2 className="font-display text-4xl font-semibold text-navy md:text-5xl">Structure the argument before polishing sentences.</h2><p className="mt-6 text-base leading-8 text-muted">The template separates intent, two pieces of relevant evidence and a professional close. This keeps the letter focused on why your experience fits this vacancy instead of repeating the whole CV.</p></div><ol className="divide-y divide-line border-y border-line">{[["Opening","Name the role, employer and one genuine reason for applying."],["Strongest evidence","Connect a specific action and result to a priority requirement."],["Second evidence","Demonstrate a different relevant skill without repeating the first example."],["Close","Summarise fit, confirm interest and invite further discussion."]].map(([title, body], index) => <li key={title} className="grid gap-4 py-5 sm:grid-cols-[44px_1fr]"><span className="inline-flex h-10 w-10 items-center justify-center rounded-md bg-paper text-sm font-bold text-navy">{index + 1}</span><div><h3 className="font-display text-2xl font-semibold text-navy">{title}</h3><p className="mt-2 text-sm leading-7 text-muted">{body}</p></div></li>)}</ol></div></section>
  <section className="border-y border-line bg-paper py-20"><div className="container-page grid gap-10 lg:grid-cols-[1fr_0.8fr]"><div><SectionLabel>Template, not boilerplate</SectionLabel><h2 className="font-display text-4xl font-semibold text-navy md:text-5xl">Every bracket requires your judgement.</h2><p className="mt-6 text-base leading-8 text-muted">Prospects advises using a basic template for ideas and structure rather than copying finished wording. Replace every prompt, verify every claim and tailor the examples to the job description.</p><p className="mt-4 text-sm font-bold text-navy">Guidance reviewed 10 July 2026.</p></div><div className="grid content-start gap-3 text-sm font-bold text-navy"><a href="https://nationalcareers.service.gov.uk/careers-advice/covering-letter" target="_blank" rel="noreferrer" className="rounded-md border border-line bg-white p-4 hover:border-navy">National Careers Service: covering letters</a><a href="https://www.prospects.ac.uk/careers-advice/cvs-and-cover-letters/cover-letters/sample-cover-letter/" target="_blank" rel="noreferrer" className="rounded-md border border-line bg-white p-4 hover:border-navy">Prospects: sample cover letter structure</a><Link href="/tools/cover-letter-generator-uk" className="rounded-md border border-line bg-white p-4 hover:border-navy">Generate a tailored cover letter</Link></div></div></section>
  <FaqSection faqs={faqs} title="UK cover letter template questions." />
  </>; }
