import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Check, Download, FileText, MonitorDown } from "lucide-react";
import { FaqSection, SectionLabel } from "@/components/marketing";
import { site } from "@/lib/site";

const path = "/tools/cv-template-word-uk";
export const metadata: Metadata = { title: "Free CV Template Word UK - DOCX Download", description: "Download a free UK CV template for Microsoft Word. Editable single-column DOCX with no signup, email gate, watermark or subscription.", alternates: { canonical: path }, openGraph: { title: "Free UK CV Template for Word", description: "Download and edit a clean UK CV template in Microsoft Word format.", url: path } };
const faqs = [
  { question: "Can I download the UK CV template as a Word file?", answer: "Yes. The button downloads a genuine .docx document that can be edited in Microsoft Word without an account, email gate or payment." },
  { question: "Can I open the CV template in Google Docs or LibreOffice?", answer: "Most modern document editors can open DOCX files, including Google Docs and LibreOffice. Formatting can vary slightly between applications, so review the final document and exported PDF." },
  { question: "Should I send a CV as Word or PDF?", answer: "Follow the employer's requested format. If no format is specified, PDF preserves the layout more consistently, while some recruiters request Word files. Keep the DOCX as your editable master." },
  { question: "Is this Word CV template ATS-friendly?", answer: "It uses one column, standard headings and ordinary document text without tables, text boxes, icons or charts. This reduces common parsing problems but cannot guarantee compatibility with every system." },
  { question: "Is the Word CV template free?", answer: "Yes. It downloads directly with no signup, watermark, subscription or email collection." },
];
const schemas = [{ "@context": "https://schema.org", "@type": "SoftwareApplication", name: "WorkCV UK CV Template for Word", applicationCategory: "BusinessApplication", operatingSystem: "Microsoft Word compatible", url: `${site.url}${path}`, fileFormat: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", offers: { "@type": "Offer", price: "0", priceCurrency: "GBP" } }, { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map((item) => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } })) }];

export default function Page() { return <>{schemas.map((schema, index) => <script key={index} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />)}
  <section className="quiet-grid border-b border-line bg-paper py-14 md:py-20"><div className="container-page grid gap-12 lg:grid-cols-[1fr_0.75fr] lg:items-center"><div><p className="mb-4 text-sm font-bold uppercase tracking-[0.14em] text-navy">Direct DOCX download</p><h1 className="font-display text-4xl font-semibold leading-[1.06] text-navy md:text-6xl">Free UK CV template for Microsoft Word.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-muted">Download an editable single-column Word document with practical UK CV headings and prompts. No account, email gate, watermark or subscription.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="/api/tools/blank-cv-template" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-md bg-navy px-6 text-sm font-bold text-white hover:bg-navy-hover"><Download className="h-4 w-4" />Download Word CV template</a><Link href="/editor?new=1" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-md border border-line-strong bg-white px-6 text-sm font-bold text-navy hover:bg-surface">Edit online instead <ArrowRight className="h-4 w-4" /></Link></div><div className="mt-6 flex flex-wrap gap-x-6 gap-y-3 text-sm font-bold text-navy"><span className="flex items-center gap-2"><FileText className="h-5 w-5 text-gold" />Real .docx file</span><span className="flex items-center gap-2"><MonitorDown className="h-5 w-5 text-success" />Immediate download</span></div></div><div className="border border-line-strong bg-white p-7 shadow-soft"><p className="text-center font-display text-2xl font-semibold text-navy">YOUR NAME</p><p className="mt-2 text-center text-xs text-muted">Town · Phone · Email · LinkedIn</p>{["PROFILE", "KEY SKILLS", "WORK EXPERIENCE", "EDUCATION"].map((heading) => <div key={heading} className="mt-6"><p className="border-b border-navy pb-1 text-xs font-bold text-navy">{heading}</p><div className="mt-3 grid gap-2"><span className="h-2 bg-line" /><span className="h-2 w-5/6 bg-line" /><span className="h-2 w-3/4 bg-line" /></div></div>)}</div></div></section>
  <section className="bg-surface py-20"><div className="container-page grid gap-12 lg:grid-cols-[0.85fr_1.15fr]"><div><SectionLabel>Edit in Word</SectionLabel><h2 className="font-display text-4xl font-semibold text-navy md:text-5xl">Keep one editable master document.</h2><p className="mt-6 text-base leading-8 text-muted">Replace the prompts, remove unused sections and tailor a copy for each application. Keep the DOCX version for future edits and export the final version in the employer’s requested format.</p></div><ol className="divide-y divide-line border-y border-line">{[["Replace every placeholder","Use your own contact details, experience, qualifications and evidence."],["Apply Word styles consistently","Keep heading, body and bullet formatting consistent instead of styling each line manually."],["Export and inspect","Open the final PDF or DOCX and check page breaks, dates, links and filename before applying."]].map(([title, body], index) => <li key={title} className="grid gap-4 py-6 sm:grid-cols-[44px_1fr]"><span className="inline-flex h-10 w-10 items-center justify-center rounded-md bg-paper text-sm font-bold text-navy">{index + 1}</span><div><h3 className="font-display text-2xl font-semibold text-navy">{title}</h3><p className="mt-2 text-sm leading-7 text-muted">{body}</p></div></li>)}</ol></div></section>
  <section className="border-y border-line bg-paper py-20"><div className="container-page grid gap-10 lg:grid-cols-[1fr_0.8fr]"><div><SectionLabel>Inside the file</SectionLabel><h2 className="font-display text-4xl font-semibold text-navy md:text-5xl">Simple enough to customise safely.</h2><p className="mt-6 text-base leading-8 text-muted">The file uses A4 sizing, one column, normal document paragraphs, standard headings and editable bullets. It deliberately avoids tables, graphics, photographs and text boxes.</p><ul className="mt-6 grid gap-3 sm:grid-cols-2">{["Contact details","Profile prompt","Skills section","Experience bullets","Education section","Additional information"].map((item) => <li key={item} className="flex gap-2 text-sm font-bold text-navy"><Check className="h-5 w-5 text-success" />{item}</li>)}</ul><p className="mt-5 text-sm font-bold text-navy">Template reviewed 10 July 2026.</p></div><div className="grid content-start gap-3 text-sm font-bold text-navy"><a href="https://nationalcareers.service.gov.uk/careers-advice/cv-sections" target="_blank" rel="noreferrer" className="rounded-md border border-line bg-white p-4 hover:border-navy">National Careers Service: UK CV sections</a><a href="https://www.reed.co.uk/career-advice/free-cv-template/" target="_blank" rel="noreferrer" className="rounded-md border border-line bg-white p-4 hover:border-navy">Reed: tailoring a Word CV template</a><Link href="/tools/blank-cv-template-uk" className="rounded-md border border-line bg-white p-4 hover:border-navy">Blank CV template guidance</Link></div></div></section>
  <FaqSection faqs={faqs} title="UK Word CV template questions." />
  </>; }
