import type { Metadata } from "next";
import Link from "next/link";
import { Banknote, MapPin, Scale } from "lucide-react";
import { LivingWageChecker2026 } from "@/components/living-wage-checker-2026";
import { FaqSection, SectionLabel } from "@/components/marketing";
import { site } from "@/lib/site";

const path = "/tools/uk-living-wage-checker-2026";
export const metadata: Metadata = { title: "UK Living Wage Checker 2026 - Hourly Pay", description: "Check hourly pay or salary against the 2026 UK minimum wage and voluntary Real Living Wage. Includes age, apprentice and London rates.", alternates: { canonical: path }, openGraph: { title: "UK Living Wage Checker 2026", description: "Compare pay with current legal and voluntary UK hourly wage benchmarks.", url: path } };
const faqs = [
  { question: "What is the UK National Living Wage in 2026?", answer: "From 1 April 2026, the statutory National Living Wage for workers aged 21 and over is £12.71 per hour. Lower National Minimum Wage rates apply to younger workers and eligible apprentices." },
  { question: "What is the Real Living Wage in 2026?", answer: "The voluntary Living Wage Foundation rates for 2025–26 are £13.45 across the UK and £14.80 in London. They are separate from the legal National Living Wage and apply to accredited employers on a voluntary basis." },
  { question: "Which apprentice rate applies?", answer: "The £8.00 apprentice rate applies to apprentices under 19, or those aged 19 and over who are in the first year of their apprenticeship. Older apprentices who have completed the first year receive the minimum rate for their age." },
  { question: "Can annual salary be below minimum wage?", answer: "Yes, if the salary divided by hours worked in the relevant pay reference period falls below the applicable legal rate. The official calculation can also be affected by unpaid time, deductions, salary sacrifice and employer-provided accommodation." },
  { question: "Is this a legal minimum-wage determination?", answer: "No. This tool provides a transparent indicative comparison. Use the GOV.UK minimum-wage calculator or seek Acas advice for a legal assessment of actual pay records." },
];
const schemas = [{ "@context": "https://schema.org", "@type": "WebApplication", name: "WorkCV UK Living Wage Checker 2026", applicationCategory: "FinanceApplication", operatingSystem: "Any", url: `${site.url}${path}`, offers: { "@type": "Offer", price: "0", priceCurrency: "GBP" } }, { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map((item) => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } })) }];

export default function Page() { return <>{schemas.map((schema, index) => <script key={index} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />)}
  <section className="quiet-grid border-b border-line bg-paper py-14 md:py-20"><div className="container-page"><div className="max-w-4xl"><p className="mb-4 text-sm font-bold uppercase tracking-[0.14em] text-navy">Current rates from April 2026</p><h1 className="font-display text-4xl font-semibold leading-[1.06] text-navy md:text-6xl">UK Living Wage Checker 2026.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-muted">Convert hourly pay or annual salary and compare it with the legal rate for your age and apprentice status, plus the voluntary Real Living Wage inside or outside London.</p><div className="mt-6 flex flex-wrap gap-x-6 gap-y-3 text-sm font-bold text-navy"><span className="flex items-center gap-2"><Scale className="h-5 w-5 text-gold" />Legal rate separated</span><span className="flex items-center gap-2"><MapPin className="h-5 w-5 text-success" />London comparison</span><span className="flex items-center gap-2"><Banknote className="h-5 w-5 text-[#63788c]" />Hourly and salary</span></div></div><div className="mt-10 rounded-lg border border-line-strong bg-surface p-5 shadow-soft md:p-7"><LivingWageChecker2026 /></div></div></section>
  <section className="bg-surface py-20"><div className="container-page grid gap-12 lg:grid-cols-[0.85fr_1.15fr]"><div><SectionLabel>Two different benchmarks</SectionLabel><h2 className="font-display text-4xl font-semibold text-navy md:text-5xl">“Living Wage” does not always mean the legal minimum.</h2><p className="mt-6 text-base leading-8 text-muted">The government’s National Living Wage is a statutory minimum for workers aged 21 and over. The Living Wage Foundation calculates higher voluntary rates from living costs, with a separate London figure.</p></div><div className="divide-y divide-line border-y border-line"><article className="py-6"><h3 className="font-display text-2xl font-semibold text-navy">Statutory National Living Wage</h3><p className="mt-2 text-sm leading-7 text-muted">£12.71 per hour for eligible workers aged 21 and over from 1 April 2026. Employers must also follow age and apprentice rates.</p></article><article className="py-6"><h3 className="font-display text-2xl font-semibold text-navy">Voluntary Real Living Wage</h3><p className="mt-2 text-sm leading-7 text-muted">£13.45 across the UK and £14.80 in London for 2025–26. These are voluntary employer commitments rather than statutory minima.</p></article></div></div></section>
  <section className="border-y border-line bg-paper py-20"><div className="container-page grid gap-10 lg:grid-cols-[1fr_0.8fr]"><div><SectionLabel>Sources and limits</SectionLabel><h2 className="font-display text-4xl font-semibold text-navy md:text-5xl">Current rates, honest calculation limits.</h2><p className="mt-6 text-base leading-8 text-muted">WorkCV compares gross pay with published hourly rates. It does not model pay reference periods, uniform costs, salary sacrifice, unpaid working time or the accommodation offset, all of which can affect legal entitlement.</p><p className="mt-4 text-sm font-bold text-navy">Rates reviewed 10 July 2026.</p></div><div className="grid content-start gap-3 text-sm font-bold text-navy"><a href="https://www.gov.uk/national-minimum-wage-rates" target="_blank" rel="noreferrer" className="rounded-md border border-line bg-white p-4 hover:border-navy">GOV.UK: current statutory rates</a><a href="https://www.gov.uk/am-i-getting-minimum-wage" target="_blank" rel="noreferrer" className="rounded-md border border-line bg-white p-4 hover:border-navy">GOV.UK: official worker calculator</a><a href="https://www.livingwage.org.uk/calculating-real-living-wage-london-and-rest-uk-2025" target="_blank" rel="noreferrer" className="rounded-md border border-line bg-white p-4 hover:border-navy">Living Wage Foundation: 2025–26 rates</a><Link href="/tools/take-home-pay-calculator-uk" className="rounded-md border border-line bg-white p-4 hover:border-navy">UK take-home pay calculator</Link></div></div></section>
  <FaqSection faqs={faqs} title="UK Living Wage questions." />
  </>; }
