"use client";
import { useEffect, useRef, useState } from "react";
import { buildTimeline, buildSelection, timelineNotes, selectionNotes, assertWorksheetSize, type TimelineDraft, type TimelineRole, type SelectionDraft } from "@/lib/career-worksheets";
import { writeCvToolHandoff } from "@/lib/cv-tool-handoff";
import { rememberCtaHandoff } from "@/lib/cta-attribution";
import type { CvToolPatch } from "@/lib/cv-tool-handoff";
import { trackFunnelEvent } from "@/components/attribution-capture";
import { site } from "@/lib/site";
import { PassOfferView } from "@/components/pass-offer-view";

const button="inline-flex min-h-11 items-center justify-center rounded border border-line-strong bg-white px-4 py-2 text-sm font-bold text-navy focus-visible:outline focus-visible:outline-2 focus-visible:outline-navy disabled:opacity-50";
const uid=()=>crypto.randomUUID();
const newEvidence=()=>({id:uid(),action:"",context:"",result:"",reminder:"",selection:"use" as const});
const newRole=(employer="",location=""):TimelineRole=>({id:uid(),employer,location,title:"",qualifier:"",start:"",end:"",current:false,evidence:[newEvidence()]});
const errorMessage=(e:unknown)=> {
 const issues=(e as {issues?:Array<{path:Array<string|number>;message:string}>})?.issues;
 const names:Record<string,string>={roles:"Role",evidence:"Evidence",requirements:"Requirement",targetRole:"Target role",start:"Start date",end:"End date",title:"Actual job title",employer:"Employer",action:"What I did",briefText:"Brief wording",requirementIds:"Linked requirements",qualifier:"Title clarification"};
 return issues?.length ? issues.map(i=>i.path.map(p=>typeof p==="number"?String(p+1):names[p]||p).join(" / ")+": "+i.message).slice(0,5).join("; ") : e instanceof Error?e.message:"Check your entries and try again.";
};
function Field({label,value,onChange,max=160,area=false,help=""}:{label:string;value:string;onChange:(v:string)=>void;max?:number;area?:boolean;help?:string}) {
 const klass="mt-1 min-h-11 w-full rounded border border-line-strong bg-white p-3 text-base leading-6 focus:outline focus:outline-2 focus:outline-navy";
 return <label className="block text-sm font-semibold">{label}{help&&<span className="mt-1 block font-normal text-muted">{help}</span>}{area?<textarea aria-label={label} className={klass+" min-h-24"} value={value} onChange={e=>onChange(e.target.value)} maxLength={max}/>:<input aria-label={label} className={klass} value={value} onChange={e=>onChange(e.target.value)} maxLength={max}/>}<span className="block text-right text-xs font-normal text-muted">{value.length}/{max}</span></label>;
}
function useLeaveProtection(dirty:boolean) {
 const leaving=useRef(false);
 useEffect(()=>{
  const before=(event:BeforeUnloadEvent)=>{if(dirty&&!leaving.current){event.preventDefault();event.returnValue="";}};
  const click=(event:MouseEvent)=>{const link=(event.target as Element)?.closest?.("a");if(dirty&&!leaving.current&&link&&link.getAttribute("href")&&!link.getAttribute("href")!.startsWith("#")&&!link.hasAttribute("download")&&link.target!=="_blank"&&!window.confirm("These notes are only in this page. Copy or download them before leaving. Leave now?")){event.preventDefault();event.stopPropagation();}};
  window.addEventListener("beforeunload",before);document.addEventListener("click",click,true);
  return()=>{window.removeEventListener("beforeunload",before);document.removeEventListener("click",click,true);};
 },[dirty]);
 return leaving;
}
function download(text:string,name:string) {const url=URL.createObjectURL(new Blob([text],{type:"text/plain;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function WorksheetFooter({text,patch,tool,stale,onError,leaving}:{text:string;patch:CvToolPatch;tool:string;stale:boolean;onError:(s:string)=>void;leaving:React.MutableRefObject<boolean>}) {
 const [copied,setCopied]=useState(false);
 const send=(pass=false)=>{if(stale)return;const dest="/editor?template=classic&new=1&from=career-tool"+(pass?"&plan=pass":"");const placement=tool+(pass?"_pass_handoff":"_outline_handoff");try{writeCvToolHandoff({source:tool,patch});}catch(e){onError(errorMessage(e)+" Copy your outline before opening the editor.");return;}
 try{rememberCtaHandoff(placement,dest);}catch{} trackFunnelEvent("marketing_cta_clicked",{placement,destination:dest});leaving.current=true;window.location.assign(dest);};
 return <div className="space-y-4">
 <label className="block font-bold">Your reviewable outline<textarea readOnly value={text} className="mt-2 min-h-72 w-full rounded border border-line-strong bg-white p-4 text-sm font-normal leading-7"/></label>
 <div className="flex flex-wrap gap-3"><button className={button} onClick={async()=>{try{await navigator.clipboard.writeText(text);setCopied(true);}catch{onError("Select the outline text and copy it manually.");}}}>Copy outline</button><button className={button} onClick={()=>download(text,tool+"-outline.txt")}>Download outline</button><button disabled={stale} className={button} onClick={()=>send()}>Review this outline in the editor</button></div>
 <p role="status" className="text-sm">{copied?"Outline copied.":""} {stale?"Your notes changed. Build the outline again before continuing.":""}</p>
 <PassOfferView placement={tool+"_pass_example"}><div className="space-y-3 rounded-lg border border-line bg-paper p-5"><h3 className="text-xl font-bold">Keep separate versions for different jobs</h3><p className="text-sm leading-7">One saved CV and matching letter costs {site.price} once. Job Search Pass is {site.passPrice} once for {site.passDays} days, with no renewal. Covered documents stay editable and downloadable afterwards.</p><button className={button} disabled={stale} onClick={()=>send(true)}>Continue with Job Search Pass selected</button></div></PassOfferView>
 <p className="text-sm leading-7">These notes stay in this page until you choose to continue. That action carries your draft in this tab for up to 30 minutes. Email-code login is required to save. Build and preview free; personalised PDF and Word downloads follow your chosen plan. Neither button starts a payment.</p>
 </div>;
}
function useWorksheetResult(tool:string) {
 const [error,setError]=useState(""); const [result,setResult]=useState<{text:string;patch:CvToolPatch;warnings:string[];snapshot:string}|null>(null);
 const ref=useRef<HTMLDivElement>(null);
 const run=(data:unknown,build:()=>{text:string;patch:CvToolPatch;warnings:string[]})=>{setError("");trackFunnelEvent("tool_started",{tool,lifecycle:"started"});try{const next=build();setResult({...next,snapshot:JSON.stringify(data)});trackFunnelEvent("tool_completed",{tool,lifecycle:"completed",result:"success"});setTimeout(()=>ref.current?.focus(),0);}catch(e){setError(errorMessage(e));trackFunnelEvent("tool_completed",{tool,lifecycle:"completed",result:"error"});setTimeout(()=>ref.current?.focus(),0);}};
 return {error,setError,result,setResult,ref,run};
}
export function CareerTimelineWorksheet() {
 const [data,setData]=useState<TimelineDraft>({version:1,targetRole:"",roles:[]});
 const [undo,setUndo]=useState<TimelineRole|null>(null);
 useEffect(()=>setData(d=>d.roles.length?d:{...d,roles:[newRole()]}),[]);
 const dirty=Boolean(data.targetRole||data.roles.some(r=>r.employer||r.location||r.qualifier||r.current||r.title||r.start||r.end||r.evidence.some(e=>e.action||e.context||e.result||e.reminder)));
 const leaving=useLeaveProtection(dirty);const w=useWorksheetResult("long_service_timeline");
 const edit=(id:string,patch:Partial<TimelineRole>)=>setData(d=>({...d,roles:d.roles.map(r=>r.id===id?{...r,...patch}:r)}));
 const add=(employer="",location="")=>{if(data.roles.length>=20){w.setError("The worksheet supports up to 20 roles.");return;}const r=newRole(employer,location);setData(d=>({...d,roles:[...d.roles,r]}));setTimeout(()=>document.getElementById("role-"+r.id)?.focus(),0);};
 const example=()=>{if(dirty&&!window.confirm("Replace these notes with the fictional example?"))return;const r=newRole("Parkside Homewares","Birmingham");setData({version:1,targetRole:"Customer Support Assistant",roles:[{...r,title:"Customer Service Assistant",start:"2009",end:"2026",evidence:[{...newEvidence(),action:"Responded to telephone and email order enquiries"},{...newEvidence(),action:"Helped colleagues learn the revised returns process",context:"Introduced in 2022"}]}]});w.setResult(null);w.setError("");};
 return <div className="space-y-6 rounded-xl border border-line bg-paper p-4 md:p-7">
 <p>Build a career timeline from your own facts. No AI, account or upload is needed. Copy or download before leaving; notes are not saved automatically.</p>
 <div className="flex flex-wrap gap-3"><button className={button} onClick={example}>Try a fictional timeline</button><button className={button} onClick={()=>{if(dirty&&!window.confirm("Clear these notes? Copy or download them first."))return;setData({version:1,targetRole:"",roles:[newRole()]});setUndo(null);w.setResult(null);w.setError("");}}>Clear worksheet</button><button className={button} onClick={()=>download(timelineNotes(data),"career-timeline-notes.txt")}>Download all notes</button></div>
 <Field label="Target role (optional)" value={data.targetRole} max={140} onChange={targetRole=>setData({...data,targetRole})}/>
 {data.roles.map((r,index)=><fieldset key={r.id} id={"role-"+r.id} tabIndex={-1} className="space-y-4 rounded-lg border border-line bg-white p-4 focus:outline focus:outline-2"><legend className="px-2 text-lg font-bold">Role {index+1}: {r.title||"your actual title"}</legend>
 <div className="grid gap-4 sm:grid-cols-2"><Field label="Employer" value={r.employer} onChange={employer=>edit(r.id,{employer})}/><Field label="Location (optional)" value={r.location} onChange={location=>edit(r.id,{location})}/><Field label="Actual job title" value={r.title} onChange={title=>edit(r.id,{title})}/><Field label="Truthful clarification (optional)" value={r.qualifier} max={100} onChange={qualifier=>edit(r.id,{qualifier})} help="Keep your official title; add context only if accurate."/><Field label="Start date" value={r.start} max={7} onChange={start=>edit(r.id,{start})} help="YYYY or YYYY-MM; do not guess months."/>{!r.current&&<Field label="End date" value={r.end} max={7} onChange={end=>edit(r.id,{end})} help="YYYY or YYYY-MM."/>}</div>
 <label className="flex min-h-11 items-center gap-2"><input type="checkbox" checked={r.current} onChange={e=>edit(r.id,{current:e.target.checked})}/>I currently work in this role</label>
 {r.evidence.map((e,i)=><fieldset key={e.id} className="space-y-3 rounded border border-line bg-paper p-4"><legend className="px-1 font-bold">Evidence {i+1}</legend><Field label="What I did" value={e.action} max={500} area onChange={action=>edit(r.id,{evidence:r.evidence.map(x=>x.id===e.id?{...x,action}:x)})}/><div className="grid gap-3 sm:grid-cols-2">{(["context","result","reminder"] as const).map(k=><Field key={k} label={k==="context"?"Context or tool (optional)":k==="result"?"Result (optional; no measured result is fine)":"Reminder/source note (kept outside CV)"} value={e[k]} max={k==="result"?300:200} onChange={v=>edit(r.id,{evidence:r.evidence.map(x=>x.id===e.id?{...x,[k]:v}:x)})}/>)}</div><label className="block">Use this evidence<select className="ml-3 min-h-11 rounded border p-2" value={e.selection} onChange={ev=>edit(r.id,{evidence:r.evidence.map(x=>x.id===e.id?{...x,selection:ev.target.value as typeof e.selection}:x)})}><option value="use">Use in CV</option><option value="notes">Keep in notes</option><option value="unsure">Unsure — review later</option></select></label><button className={button} disabled={r.evidence.length===1} onClick={()=>{if(e.action&&!window.confirm("Remove this evidence?"))return;edit(r.id,{evidence:r.evidence.filter(x=>x.id!==e.id)});}}>Remove evidence {i+1}</button></fieldset>)}
 <div className="flex flex-wrap gap-3"><button className={button} disabled={r.evidence.length>=8} onClick={()=>edit(r.id,{evidence:[...r.evidence,newEvidence()]})}>Add evidence (up to 8)</button><button className={button} onClick={()=>add(r.employer,r.location)}>Add role at this employer</button><button className={button} disabled={index===0} onClick={()=>setData(d=>{const roles=[...d.roles];[roles[index-1],roles[index]]=[roles[index],roles[index-1]];return {...d,roles};})}>Move role up</button><button className={button} disabled={index===data.roles.length-1} onClick={()=>setData(d=>{const roles=[...d.roles];[roles[index+1],roles[index]]=[roles[index],roles[index+1]];return {...d,roles};})}>Move role down</button><button className={button} disabled={data.roles.length===1} onClick={()=>{setUndo(r);setData(d=>({...d,roles:d.roles.filter(x=>x.id!==r.id)}));setTimeout(()=>document.getElementById("add-employer")?.focus(),0);}}>Remove role</button></div>
 </fieldset>)}
 <div className="flex flex-wrap gap-3"><button id="add-employer" className={button} onClick={()=>add()}>Add another employer</button>{undo&&<button className={button} disabled={data.roles.length>=20} onClick={()=>{setData(d=>({...d,roles:[...d.roles,undo]}));setUndo(null);}}>Undo removed role</button>}<button className={button+" !bg-navy !text-white"} onClick={()=>w.run(data,()=>buildTimeline(data))}>Build my outline</button></div>
 <div ref={w.ref} tabIndex={-1} className="space-y-4">{w.error&&<p role="alert" className="rounded border border-red-300 bg-red-50 p-4">{w.error}</p>}{w.result&&<><h3 className="text-2xl font-bold">Review your career timeline</h3>{w.result.warnings.map(x=><p key={x} className="rounded border border-line bg-white p-3">{x}</p>)}<WorksheetFooter text={w.result.text} patch={w.result.patch} tool="long_service_timeline" stale={w.result.snapshot!==JSON.stringify(data)} onError={w.setError} leaving={leaving}/></>}</div>
 </div>;
}
const newCard=()=>({id:uid(),originalText:"",role:"",employer:"",dateContext:"",requirementIds:[] as string[],selection:"unsure" as const,briefText:""});
export function EvidenceSelector() {
 const [data,setData]=useState<SelectionDraft>({version:1,targetRole:"",requirements:[],evidence:[],motivation:""});
 const [versions,setVersions]=useState<Array<{id:string;label:string;draft:SelectionDraft}>>([]);
 const [undo,setUndo]=useState<SelectionDraft["evidence"][number]|null>(null);
 useEffect(()=>setData(d=>d.requirements.length?d:{...d,requirements:[{id:uid(),text:""}],evidence:[newCard()]}),[]);
 const dirty=Boolean(versions.length||data.targetRole||data.motivation||data.evidence.some(e=>e.originalText||e.role||e.employer||e.dateContext||e.briefText)||data.requirements.some(r=>r.text));
 const leaving=useLeaveProtection(dirty);const w=useWorksheetResult("evidence_selector");
 const edit=(id:string,patch:Partial<SelectionDraft["evidence"][number]>)=>setData(d=>({...d,evidence:d.evidence.map(e=>e.id===id?{...e,...patch}:e)}));
 const example=()=>{if(dirty&&!window.confirm("Replace these notes with the fictional example?"))return;const requirement={id:uid(),text:"Coordinate meeting rooms and supplier records"};setData({version:1,targetRole:"Office Coordinator",requirements:[requirement],motivation:"I want to focus on hands-on coordination rather than supervising staff.",evidence:[{...newCard(),originalText:"Coordinated meeting-room bookings and maintained supplier records.",role:"Office Manager",employer:"Pennfield Design",dateContext:"2019-03 to 2026-09",selection:"lead",requirementIds:[requirement.id]}]});w.setResult(null);};
 return <div className="space-y-6 rounded-xl border border-line bg-paper p-4 md:p-7"><p>Choose evidence for this job. You decide relevance; this worksheet does not score your seniority or verify competence. Notes stay in memory on this page. Copy or download before leaving.</p>
 <div className="flex flex-wrap gap-3"><button className={button} onClick={example}>Try a fictional selection</button><button className={button} onClick={()=>download(selectionNotes(data),"application-master-notes.txt")}>Download all original notes</button><button className={button} onClick={()=>{if(dirty&&!window.confirm("Clear these notes and local versions?"))return;setData({version:1,targetRole:"",motivation:"",requirements:[{id:uid(),text:""}],evidence:[newCard()]});setVersions([]);setUndo(null);w.setResult(null);}}>Clear worksheet</button></div>
 <Field label="Target role" max={140} value={data.targetRole} onChange={targetRole=>setData({...data,targetRole})}/>
 <fieldset className="space-y-3"><legend className="text-lg font-bold">Vacancy requirements (up to 8)</legend>{data.requirements.map((r,i)=><div key={r.id} className="space-y-2"><Field label={"Requirement "+(i+1)} value={r.text} max={240} area onChange={text=>setData({...data,requirements:data.requirements.map(x=>x.id===r.id?{...x,text}:x)})}/><button className={button} disabled={data.requirements.length===1} onClick={()=>setData({...data,requirements:data.requirements.filter(x=>x.id!==r.id),evidence:data.evidence.map(e=>({...e,requirementIds:e.requirementIds.filter(id=>id!==r.id)}))})}>Remove requirement {i+1}</button></div>)}<button className={button} disabled={data.requirements.length>=8} onClick={()=>setData({...data,requirements:[...data.requirements,{id:uid(),text:""}]})}>Add requirement</button></fieldset>
 {data.evidence.map((e,i)=><fieldset key={e.id} className="space-y-4 rounded-lg border border-line bg-white p-4"><legend className="px-2 text-lg font-bold">Evidence {i+1}</legend><Field label="Original fact — keep it accurate" value={e.originalText} max={600} area onChange={originalText=>edit(e.id,{originalText})}/><div className="grid gap-4 sm:grid-cols-3">{(["role","employer","dateContext"] as const).map(k=><Field key={k} label={k==="role"?"Actual job title (optional)":k==="employer"?"Employer (optional)":"Dates/context (optional)"} value={e[k]} onChange={v=>edit(e.id,{[k]:v})}/>)}</div>
 <fieldset><legend className="font-semibold">Which requirements does this support?</legend>{data.requirements.map((r,j)=><label key={r.id} className="flex min-h-11 items-center gap-3"><input type="checkbox" checked={e.requirementIds.includes(r.id)} onChange={ev=>edit(e.id,{requirementIds:ev.target.checked?[...e.requirementIds,r.id]:e.requirementIds.filter(id=>id!==r.id)})}/>{r.text||"Requirement "+(j+1)}</label>)}</fieldset>
 <label className="block font-semibold">How to use this fact<select className="ml-3 min-h-11 max-w-full rounded border p-2" value={e.selection} onChange={ev=>edit(e.id,{selection:ev.target.value as typeof e.selection})}><option value="lead">Lead with it</option><option value="brief">Include briefly</option><option value="notes">Keep in master notes</option><option value="unsure">Unsure — review later</option></select></label>
 {e.selection==="brief"&&<Field label="Your brief wording (original stays above)" max={300} area value={e.briefText} onChange={briefText=>edit(e.id,{briefText})}/>}
 <button className={button} disabled={data.evidence.length===1} onClick={()=>{setUndo(e);setData({...data,evidence:data.evidence.filter(x=>x.id!==e.id)});setTimeout(()=>document.getElementById("add-evidence")?.focus(),0);}}>Remove evidence {i+1}</button></fieldset>)}
 <div className="flex flex-wrap gap-3"><button id="add-evidence" className={button} disabled={data.evidence.length>=20} onClick={()=>setData({...data,evidence:[...data.evidence,newCard()]})}>Add evidence (up to 20)</button>{undo&&<button className={button} disabled={data.evidence.length>=20} onClick={()=>{setData({...data,evidence:[...data.evidence,undo]});setUndo(null);}}>Undo removed evidence</button>}</div>
 <Field label="Genuine reason for applying (optional)" value={data.motivation} max={500} area help="Use your own reason. Do not promise salary acceptance or long-term commitment unless true." onChange={motivation=>setData({...data,motivation})}/>
 <div className="flex flex-wrap gap-3"><button className={button+" !bg-navy !text-white"} onClick={()=>w.run(data,()=>{const r=buildSelection(data);return {...r,warnings:r.unmatched.map(x=>"No selected evidence linked: "+x)};})}>Build my selection</button><button className={button} disabled={versions.length>=5} onClick={()=>{try{const next=[...versions,{id:uid(),label:data.targetRole||"Untitled selection",draft:structuredClone(data)}];assertWorksheetSize({data,versions:next});setVersions(next);}catch(e){w.setError(errorMessage(e));}}}>Keep a local copy for another version</button></div>
 {versions.length>0&&<fieldset className="space-y-2"><legend className="font-bold">Local versions (lost when this page closes; up to 5)</legend>{versions.map((v,i)=><div key={v.id} className="flex flex-wrap gap-3"><button className={button} onClick={()=>{if(dirty&&!window.confirm("Load this local copy? Download or keep your current selection first."))return;setData(structuredClone(v.draft));w.setResult(null);}}>Load {i+1}: {v.label}</button><button className={button} onClick={()=>download(selectionNotes(v.draft),"application-version-"+(i+1)+".txt")}>Download version {i+1}</button><button className={button} onClick={()=>{if(window.confirm("Remove this local version?"))setVersions(versions.filter(x=>x.id!==v.id));}}>Remove version {i+1}</button></div>)}</fieldset>}
 <div ref={w.ref} tabIndex={-1} className="space-y-4">{w.error&&<p role="alert" className="rounded border border-red-300 bg-red-50 p-4">{w.error}</p>}{w.result&&<><h3 className="text-2xl font-bold">Your evidence selection</h3>{w.result.warnings.map(x=><p key={x} className="rounded border border-line bg-white p-3">{x}</p>)}<p className="text-sm">Only selected bullets go into the editor's review notes. Your original facts remain separate; assign each bullet to the correct real job. No missing employment details are invented.</p><WorksheetFooter text={w.result.text} patch={w.result.patch} tool="evidence_selector" stale={w.result.snapshot!==JSON.stringify(data)} onError={w.setError} leaving={leaving}/></>}</div>
 </div>;
}
