"use client";

import Link from "next/link";
import { FormEvent, useMemo, useRef, useState } from "react";
import { AlertTriangle, ArrowRight, Hash, RotateCcw, ShieldCheck, Tags } from "lucide-react";
import { analyseCvKeywordDensity, cvWords, KeywordDensityAnalysis } from "@/lib/cv-text-analysis";

const example = `Customer service team leader with experience improving customer service across phone and email channels. Led eight customer service advisers and coached four new starters. Reviewed service data each week, resolved customer complaints and introduced a complaint triage process. The new process reduced overdue complaints by 18%. Used Salesforce to maintain customer records and report recurring service issues.`;

export function CvKeywordDensityChecker() {
  const [text, setText] = useState(""); const [result, setResult] = useState<KeywordDensityAnalysis | null>(null); const [error, setError] = useState(""); const resultRef = useRef<HTMLDivElement>(null); const words = useMemo(() => cvWords(text).length, [text]);
  function submit(event: FormEvent) { event.preventDefault(); setError(""); if (words < 50) { setResult(null); setError("Paste at least 50 words so repeated terms can be interpreted usefully."); return; } setResult(analyseCvKeywordDensity(text)); window.setTimeout(() => resultRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }), 0); }
  return <div><form onSubmit={submit}><label className="block"><span className="flex items-end justify-between gap-3"><span><span className="block text-sm font-bold text-navy">Paste your CV text</span><span className="mt-1 block text-xs leading-5 text-muted">The checker removes common words before ranking repeated terms.</span></span><span className="text-xs font-bold text-muted">{words} words</span></span><textarea value={text} onChange={(event) => setText(event.target.value)} maxLength={40000} placeholder="Paste your complete CV text here..." className="mt-3 min-h-[340px] w-full resize-y rounded-md border border-line-strong bg-white p-4 text-[16px] leading-7 text-ink outline-none placeholder:text-muted/70 focus:border-navy focus:ring-2 focus:ring-navy/15" /></label>{error ? <div role="alert" className="mt-4 flex gap-3 rounded-md border border-[#efc3c3] bg-redsoft p-4 text-sm font-bold text-[#8d3030]"><AlertTriangle className="h-5 w-5 shrink-0" />{error}</div> : null}<div className="mt-5 flex flex-col gap-4 border-t border-line pt-5 sm:flex-row sm:items-center sm:justify-between"><p className="flex max-w-xl gap-2 text-xs leading-5 text-muted"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-success" />Runs in your browser. WorkCV does not upload or save the text.</p><div className="flex flex-wrap gap-2"><button type="button" onClick={() => { setText(example); setResult(null); setError(""); }} className="min-h-11 rounded-md border border-line-strong bg-white px-4 text-sm font-bold text-navy hover:bg-paper">Try example</button>{text ? <button type="button" onClick={() => { setText(""); setResult(null); setError(""); }} aria-label="Clear CV text" title="Clear CV text" className="inline-flex h-11 w-11 items-center justify-center rounded-md border border-line-strong text-navy hover:bg-paper"><RotateCcw className="h-4 w-4" /></button> : null}<button type="submit" className="inline-flex min-h-11 items-center gap-2 rounded-md bg-navy px-5 text-sm font-bold text-white hover:bg-navy-hover">Analyse repetition <ArrowRight className="h-4 w-4" /></button></div></div></form>
  {result ? <div ref={resultRef} className="scroll-mt-24 pt-12" aria-live="polite"><section className="border-y border-line-strong py-7"><div className="grid gap-6 sm:grid-cols-3"><div><p className="text-xs font-bold uppercase text-muted">Words analysed</p><p className="mt-2 font-display text-4xl font-semibold text-navy">{result.wordCount}</p></div><div><p className="text-xs font-bold uppercase text-muted">Unique meaningful words</p><p className="mt-2 font-display text-4xl font-semibold text-navy">{result.uniqueWordRatio}%</p></div><div><p className="text-xs font-bold uppercase text-muted">Repeated phrases</p><p className="mt-2 font-display text-4xl font-semibold text-navy">{result.repeatedPhrases.length}</p></div></div>
  <div className="mt-8 grid gap-8 lg:grid-cols-2"><div><h2 className="flex items-center gap-2 font-display text-2xl font-semibold text-navy"><Hash className="h-5 w-5 text-gold" />Most repeated words</h2>{result.repeatedTerms.length ? <div className="mt-4 divide-y divide-line border-y border-line">{result.repeatedTerms.slice(0, 12).map((item) => <div key={item.term} className="grid grid-cols-[1fr_auto_auto] items-center gap-4 py-3 text-sm"><span className="font-bold text-ink">{item.term}</span><span className="text-muted">{item.count} uses</span><span className="w-16 text-right font-bold text-navy">{item.density}%</span></div>)}</div> : <p className="mt-4 text-sm text-muted">No meaningful word appears more than once.</p>}</div><div><h2 className="flex items-center gap-2 font-display text-2xl font-semibold text-navy"><Tags className="h-5 w-5 text-gold" />Repeated phrases</h2>{result.repeatedPhrases.length ? <div className="mt-4 divide-y divide-line border-y border-line">{result.repeatedPhrases.map((item) => <div key={item.term} className="grid grid-cols-[1fr_auto] gap-4 py-3 text-sm"><span className="font-bold text-ink">{item.term}</span><span className="text-muted">{item.count} uses</span></div>)}</div> : <p className="mt-4 text-sm text-muted">No two- or three-word phrase is repeated.</p>}</div></div>
  <div className="mt-8 grid gap-5 lg:grid-cols-2"><div className="border-l-4 border-gold bg-paper p-5"><h3 className="font-display text-xl font-semibold text-navy">Wording to review</h3>{result.overusedPhrases.length ? <ul className="mt-3 space-y-2 text-sm text-ink">{result.overusedPhrases.map((phrase) => <li key={phrase}>• “{phrase}”</li>)}</ul> : <p className="mt-3 text-sm leading-7 text-muted">No common vague phrase from this checker’s list was found.</p>}</div><div className="border-l-4 border-success bg-[#edf7f1] p-5"><h3 className="font-display text-xl font-semibold text-navy">Interpretation</h3><p className="mt-3 text-sm leading-7 text-muted">Repeated role-specific terms can be appropriate. Review repetition when it makes several bullets sound identical or replaces concrete evidence. There is no universal “safe” keyword percentage.</p></div></div>
  <div className="mt-8 flex flex-col gap-4 border-t border-line pt-6 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm text-muted">Need to compare these terms with an actual vacancy?</p><Link href="/tools/ats-score-checker" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-md bg-navy px-4 text-sm font-bold text-white">Open ATS checker <ArrowRight className="h-4 w-4" /></Link></div></section></div> : null}</div>;
}
