"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { AlertTriangle, ArrowRight, Check, Info, X } from "lucide-react";
import { calculateLivingWage2026, LivingWageResult } from "@/lib/living-wage-2026";

const money = (value: number) => value.toLocaleString("en-GB", { style: "currency", currency: "GBP", minimumFractionDigits: 2 });

export function LivingWageChecker2026() {
  const [payType, setPayType] = useState<"hourly" | "annual">("hourly");
  const [pay, setPay] = useState("12.71"); const [hours, setHours] = useState("37.5"); const [weeks, setWeeks] = useState("52"); const [age, setAge] = useState("25");
  const [apprentice, setApprentice] = useState(false); const [firstYear, setFirstYear] = useState(false); const [location, setLocation] = useState<"london" | "rest-uk">("rest-uk");
  const [result, setResult] = useState<LivingWageResult | null>(null); const [error, setError] = useState("");
  function submit(event: FormEvent) { event.preventDefault(); setError(""); try { setResult(calculateLivingWage2026({ payType, pay: Number(pay), paidHoursPerWeek: Number(hours), paidWeeksPerYear: Number(weeks), age: Number(age), apprentice, firstApprenticeshipYear: firstYear, location })); } catch (problem) { setResult(null); setError(problem instanceof Error ? problem.message : "Check the figures and try again."); } }
  const field = "mt-2 min-h-12 w-full rounded-md border border-line-strong bg-white px-4 text-[16px] text-ink outline-none focus:border-navy focus:ring-2 focus:ring-navy/15";
  return <div><form onSubmit={submit}><fieldset><legend className="text-sm font-bold text-navy">How are you paid?</legend><div className="mt-2 grid min-h-12 grid-cols-2 rounded-md border border-line-strong bg-white p-1">{([['hourly','Hourly rate'],['annual','Annual salary']] as const).map(([value, label]) => <button key={value} type="button" aria-pressed={payType === value} onClick={() => { setPayType(value); setPay(value === "hourly" ? "12.71" : "26000"); setResult(null); }} className={`rounded px-3 text-sm font-bold ${payType === value ? "bg-navy text-white" : "text-muted hover:bg-paper"}`}>{label}</button>)}</div></fieldset>
  <div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><label className="text-sm font-bold text-navy">{payType === "hourly" ? "Gross hourly rate" : "Gross annual salary"}<span className="relative mt-2 block"><span className="absolute left-4 top-1/2 -translate-y-1/2 text-muted">£</span><input type="number" min="0.01" step="0.01" required value={pay} onChange={(event) => setPay(event.target.value)} className={`${field} mt-0 pl-8`} /></span></label><label className="text-sm font-bold text-navy">Paid hours per week<input type="number" min="0.1" max="100" step="0.1" required value={hours} onChange={(event) => setHours(event.target.value)} className={field} /></label><label className="text-sm font-bold text-navy">Paid weeks per year<input type="number" min="1" max="53" step="1" required value={weeks} onChange={(event) => setWeeks(event.target.value)} className={field} /></label><label className="text-sm font-bold text-navy">Age<input type="number" min="16" max="100" step="1" required value={age} onChange={(event) => setAge(event.target.value)} className={field} /></label></div>
  <div className="mt-6 grid gap-6 border-t border-line pt-6 md:grid-cols-2"><fieldset><legend className="text-sm font-bold text-navy">Location for voluntary Living Wage</legend><div className="mt-2 grid min-h-12 grid-cols-2 rounded-md border border-line-strong bg-white p-1">{([['rest-uk','Outside London'],['london','London']] as const).map(([value, label]) => <button key={value} type="button" aria-pressed={location === value} onClick={() => setLocation(value)} className={`rounded px-3 text-sm font-bold ${location === value ? "bg-navy text-white" : "text-muted hover:bg-paper"}`}>{label}</button>)}</div></fieldset><div><label className="flex min-h-12 items-center gap-3 rounded-md border border-line-strong bg-white px-4 text-sm font-bold text-navy"><input type="checkbox" checked={apprentice} onChange={(event) => { setApprentice(event.target.checked); if (!event.target.checked) setFirstYear(false); }} className="h-4 w-4 accent-navy" />I am an apprentice</label>{apprentice && Number(age) >= 19 ? <label className="mt-2 flex min-h-12 items-center gap-3 rounded-md border border-line-strong bg-white px-4 text-sm font-bold text-navy"><input type="checkbox" checked={firstYear} onChange={(event) => setFirstYear(event.target.checked)} className="h-4 w-4 accent-navy" />I am in the first year of my apprenticeship</label> : null}</div></div>
  {error ? <div role="alert" className="mt-5 flex gap-3 rounded-md border border-[#efc3c3] bg-redsoft p-4 text-sm font-bold text-[#8d3030]"><AlertTriangle className="h-5 w-5 shrink-0" />{error}</div> : null}<div className="mt-6 flex flex-col gap-4 border-t border-line pt-5 sm:flex-row sm:items-center sm:justify-between"><p className="flex max-w-xl gap-2 text-xs leading-5 text-muted"><Info className="mt-0.5 h-4 w-4 shrink-0" />Indicative comparison only. Deductions, unpaid time and employer accommodation can change the legal calculation.</p><button type="submit" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-md bg-navy px-5 text-sm font-bold text-white hover:bg-navy-hover">Check my pay <ArrowRight className="h-4 w-4" /></button></div></form>
  {result ? <section className="mt-12 border-y border-line-strong py-7" aria-live="polite"><div className="grid gap-6 md:grid-cols-3"><div><p className="text-xs font-bold uppercase text-muted">Your effective hourly pay</p><p className="mt-2 font-display text-5xl font-semibold text-navy">{money(result.effectiveHourlyPay)}</p><p className="mt-2 text-sm text-muted">{money(result.annualGrossPay)} gross per year</p></div><ResultBlock title={result.statutoryLabel} rate={result.statutoryRate} meets={result.meetsStatutoryRate} difference={result.statutoryDifferencePerHour} legal /><ResultBlock title={result.realLivingWageLabel} rate={result.realLivingWageRate} meets={result.meetsRealLivingWage} difference={result.realLivingDifferencePerHour} /></div>
  <div className="mt-8 grid gap-5 sm:grid-cols-2"><div className="border-l-4 border-navy bg-paper p-5"><p className="text-xs font-bold uppercase text-muted">Statutory annual equivalent</p><p className="mt-2 font-display text-3xl font-semibold text-navy">{money(result.statutoryAnnualEquivalent)}</p><p className="mt-2 text-xs leading-6 text-muted">At your entered hours and paid weeks.</p></div><div className="border-l-4 border-gold bg-paper p-5"><p className="text-xs font-bold uppercase text-muted">Voluntary Living Wage equivalent</p><p className="mt-2 font-display text-3xl font-semibold text-navy">{money(result.realLivingAnnualEquivalent)}</p><p className="mt-2 text-xs leading-6 text-muted">At your entered hours and paid weeks.</p></div></div>
  <div className="mt-8 flex flex-col gap-4 border-t border-line pt-6 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm leading-7 text-muted">For a legal minimum-wage assessment covering deductions and pay reference periods, use the official GOV.UK calculator.</p><a href="https://www.gov.uk/am-i-getting-minimum-wage" target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-md border border-line-strong bg-white px-4 text-sm font-bold text-navy hover:border-navy">Official wage calculator <ArrowRight className="h-4 w-4" /></a></div><div className="mt-5 text-sm"><Link href="/tools/take-home-pay-calculator-uk" className="font-bold text-navy underline">Estimate take-home pay from this salary</Link></div></section> : null}</div>;
}

function ResultBlock({ title, rate, meets, difference, legal = false }: { title: string; rate: number; meets: boolean; difference: number; legal?: boolean }) {
  return <div className={`border-l-4 p-5 ${meets ? "border-success bg-[#edf7f1]" : "border-[#b54242] bg-redsoft"}`}><div className="flex items-center gap-2 text-sm font-bold text-navy">{meets ? <Check className="h-4 w-4 text-success" /> : <X className="h-4 w-4 text-[#b54242]" />}{meets ? "Meets rate" : "Below rate"}</div><h2 className="mt-3 font-display text-xl font-semibold text-navy">{title}</h2><p className="mt-2 font-display text-3xl font-semibold text-navy">{money(rate)}/hour</p><p className="mt-2 text-xs leading-6 text-muted">{difference >= 0 ? `${money(difference)} above per hour` : `${money(Math.abs(difference))} below per hour`}{legal ? " · legal minimum for the entered age/status" : " · voluntary benchmark"}</p></div>;
}
