export type FirstJobExample = {
  name: string; role: string; employer: string; town: string; profile: string;
  education: string; skills: string[]; experience: { heading: string; dates: string; bullets: string[] }[];
  letter: string[]; why: string[];
};
export const firstJobExamples: Record<string, FirstJobExample> = {
  retail: {
    name: "Alex Morgan", role: "Retail Assistant", employer: "Elmbridge Homeware", town: "Birmingham",
    profile: "School leaver seeking a first paid retail role. Helped visitors at a school fundraising sale, kept donated items organised and checked price labels with the event organiser. Brings experience explaining information clearly and sharing tasks with other volunteers.",
    education: "Elmbridge School, Birmingham — GCSEs including English Language and Mathematics, September 2021–June 2026.",
    skills: ["Visitor help: listened to questions and directed visitors to the right stall.", "Accuracy: checked donated-item labels against the organiser's price list.", "Teamwork: agreed setup tasks and told the next volunteer what remained to do."],
    experience: [{ heading: "School fundraising sale — volunteer", dates: "May 2026", bullets: ["Sorted donated books and household items into labelled groups before the sale.", "Welcomed visitors, explained where to find items and asked the organiser to answer questions outside my responsibility.", "Checked display labels against the price list and flagged missing labels before opening.", "Helped tidy the stalls and handed remaining tasks to the next volunteer."] }, { heading: "School group presentation — project", dates: "March 2026", bullets: ["Prepared a short presentation with three classmates and agreed who would explain each section.", "Checked the slides for missing information and practised answering questions with the group."] }],
    letter: ["I am applying for the Retail Assistant role at Elmbridge Homeware. Your vacancy asks for helpful customer service, tidy displays and teamwork, which I have practised through a school fundraising sale and group projects.", "At the May 2026 sale I welcomed visitors, helped them find the right stall and asked the organiser when I could not answer a question. Before opening, I sorted donated items and checked display labels against the price list. I also shared setup and tidying tasks with other volunteers.", "I finished my GCSEs at Elmbridge School in June 2026 and am looking for my first paid role. I have not operated a shop till or handled refunds, so would need training in your procedures. I would welcome the chance to discuss the role and the shifts you need covered. Thank you for considering my application."],
    why: ["The letter uses the same sale, tasks and education as the CV; volunteering is labelled clearly.", "Helping visitors is relevant customer-facing evidence without claiming paid retail employment.", "It does not invent till experience, sales targets or unrestricted availability."],
  },
};

firstJobExamples.warehouse = {
  name: "Jordan Evans", role: "Warehouse Operative", employer: "Northfield Distribution", town: "Coventry",
  profile: "School leaver seeking a first paid warehouse role. Volunteered at a community food collection, checking donated items against a list, sorting labelled boxes and keeping the work area clear. Used written instructions and reported discrepancies to the organiser.",
  education: "Northfield School, Coventry — GCSEs including English Language and Mathematics, September 2021–June 2026.",
  skills: ["Checking items: compared donated goods with the collection list and flagged differences.", "Following instructions: sorted labelled boxes into the organiser's assigned areas.", "Clear handovers: recorded unfinished checks so the next volunteer knew what remained."],
  experience: [{ heading: "Community food collection — volunteer", dates: "July–August 2026", bullets: ["Checked donated items against the collection list and asked the organiser about missing or unclear entries.", "Sorted labelled boxes into assigned areas using written instructions.", "Kept packaging out of walkways and asked for help with items I could not move safely.", "Recorded unfinished checks before handing over to the next volunteer."] }, { heading: "School design project — group task", dates: "April 2026", bullets: ["Compared the project materials with a written list before the group started work.", "Returned unused materials to their labelled storage places at the end of each session."] }],
  letter: ["I am applying for the Warehouse Operative role at Northfield Distribution. Your advert asks for careful checking, following instructions and clear handovers. My volunteering at a community food collection gave me experience practising those habits.", "During July and August 2026 I checked donated items against a list, sorted labelled boxes into assigned areas and referred unclear entries to the organiser. I kept packaging out of walkways, asked for help when needed and recorded unfinished checks for the next volunteer.", "I completed my GCSEs at Northfield School in June 2026 and am seeking my first paid role. I have not used warehouse scanners or powered equipment and do not hold a forklift certificate. I would need the training required for your tasks. I would welcome a discussion about the shift pattern and duties. Thank you for considering my application."],
  why: ["The CV and letter both use the same food collection and school project, with matching dates.", "The example shows checking and following instructions without inventing warehouse employment or productivity figures.", "It states the equipment gap. Awareness of safety is not a licence, certificate or proof that a person can perform every physical duty."],
};
