import { TailoringEvidenceBank } from "@/components/tailoring-evidence-bank";
import type { Metadata } from "next";
import Link from "next/link";
import { ButtonLink, FaqSection } from "@/components/marketing";
import { PassOffer } from "@/components/pass-offer";
import { site } from "@/lib/site";

const path = "/tailor-cv-to-job-description-uk";
export const metadata: Metadata = {
  title: "How to Tailor Your CV to a Job Description: UK Examples",
  description: "See one applicant adapt a CV and matching letter for two UK vacancies. Worked profiles, evidence mapping, bullet edits and a checklist using truthful experience.",
  alternates: { canonical: path },
};
const examples = [
  {
    id: "customer-service", role: "Customer Service Adviser", employer: "Northbank Homeware",
    advert: "Answer product enquiries, explain stock availability and leave clear notes for colleagues. This fictional vacancy asks for customer-facing experience and a calm telephone manner; CRM experience is desirable.",
    profile: "Retail assistant with experience answering product enquiries, checking stock and explaining the next step to customers. Keeps clear shift handovers and refers questions outside their responsibility to a supervisor. Seeking a customer service adviser role where helpful explanations and reliable follow-through matter.",
    bullets: ["Answered product questions on the shop floor, checked stock with colleagues and explained the available alternatives.", "Passed unresolved enquiries and agreed next steps to the next shift so colleagues could follow up.", "Updated shelf labels against the current price list and asked a supervisor to resolve discrepancies."],
    letter: ["I am applying for the Customer Service Adviser role at Northbank Homeware. Your advert's focus on product enquiries and clear handovers fits the customer-facing work I do at Westbridge Stores.", "When a customer asks about an unavailable item, I check with colleagues and explain the alternatives. I also pass unresolved enquiries and agreed next steps to the next shift. These are the habits I would bring to keeping customers informed and giving colleagues useful notes.", "My experience has been face to face rather than in a contact centre, and I have not used a CRM. I would welcome training in your systems and telephone procedures. Thank you for considering my application."],
    explanation: "The profile leads with enquiries. The price-checking bullet stays, but moves below customer evidence. The letter acknowledges the telephone and CRM gap instead of claiming experience Sam does not have.",
  },
  {
    id: "admin", role: "Junior Administrator", employer: "Eastmere Community Centre",
    advert: "Maintain booking records, check names and dates, update spreadsheets and pass queries to the right colleague. This fictional vacancy accepts transferable experience and asks for basic Excel use, not advanced formulas.",
    profile: "Retail assistant and community-event volunteer with experience checking price lists and maintaining an attendee spreadsheet. Uses basic Excel sorting and filters to review entries, and shares clear notes with colleagues. Seeking a junior administration role focused on accurate records and organised follow-up.",
    bullets: ["Updated shelf labels against the current price list and asked a supervisor to resolve discrepancies.", "Passed unresolved enquiries and agreed next steps to the next shift so colleagues could follow up.", "Answered product questions on the shop floor, checked stock with colleagues and explained the available alternatives."],
    letter: ["I am applying for the Junior Administrator role at Eastmere Community Centre. The emphasis on checking booking details and keeping records current interests me because I have carried out similar checks in retail and community volunteering.", "For Westbridge Community Events I maintain the attendee list in Excel, check names and dates against registration forms, and flag unclear entries to the organiser. I use sorting and filters to review the list. At Westbridge Stores I also check shelf labels against the current price list and refer discrepancies to a supervisor.", "I would bring these checking habits and clear handover notes to your booking team. I have not yet used a booking system, so would need to learn your process. Thank you for considering my application."],
    explanation: "The profile now leads with record checking. The retail job remains the same job, with the same dates. The volunteering section becomes especially relevant; basic Excel is not upgraded into advanced analysis.",
  },
];
const faqs = [
  { question: "Should I change my CV for every job?", answer: "Review it against every advert. Similar jobs may need only a different profile and reordered bullets. Keep employers, dates, qualifications and the facts of your experience consistent." },
  { question: "How do I tailor a CV with no work experience?", answer: "Use a school project, volunteering, a club or another real responsibility. Name the setting honestly, describe what you did and connect it to a requirement. Do not turn a project into a paid job." },
  { question: "Should I include every keyword from the job description?", answer: "No. Use relevant wording only where it accurately describes your experience. Do not add qualifications, licences, systems or responsibilities just because the advert mentions them." },
  { question: "Do I need to buy a new CV for each application?", answer: `No. WorkCV's ${site.price} option lets you edit and redownload the same saved CV and letter. The ${site.passPrice} Pass is useful if you want separate saved versions; it covers new CVs during ${site.passDays} days.` },
];
export default function TailorCvPage() {
  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ "@context": "https://schema.org", "@type": "Article", headline: metadata.title, description: metadata.description, datePublished: "2026-10-02", dateModified: "2026-10-05", author: { "@type": "Organization", name: "WorkCV", url: `${site.url}/about` }, mainEntityOfPage: `${site.url}${path}` }) }} />
    <section className="quiet-grid border-b border-line bg-paper py-12 md:py-20"><div className="container-page max-w-5xl">
      <p className="text-sm font-bold uppercase tracking-wide text-navy">UK CV writing • Worked examples</p>
      <h1 className="mt-4 font-display text-4xl font-semibold leading-tight text-navy md:text-6xl">Tailor your CV to a job advert—with a worked example.</h1>
      <p className="mt-6 text-lg leading-8 text-muted">Identify the advert&apos;s main requirements, match them to evidence you actually have, then adjust your profile, skills and bullet order. Keep employers, dates and qualifications accurate. Check that your cover letter agrees with the revised CV.</p>
      <nav aria-label="Guide sections" className="mt-6 flex flex-wrap gap-4 font-bold underline"><a href="#evidence">Start with the facts</a><a href="#customer-service">Customer service version</a><a href="#admin">Admin version</a><a href="#save-versions">Save your versions</a></nav>
      <p className="mt-5 text-sm text-muted">Written by WorkCV • Reviewed 5 October 2026. All people, employers and vacancy briefs below are fictional illustrations.</p>
    </div></section>
    <section id="evidence" className="scroll-mt-24 bg-white py-12"><div className="container-page max-w-5xl space-y-6">
      <h2 className="font-display text-3xl font-semibold text-navy">1. Make an evidence bank before editing</h2>
      <p className="leading-8">Sam Taylor lives in Leeds and works as a Retail Assistant at Westbridge Stores, June 2024–present. Sam also volunteers for Westbridge Community Events, January 2025–present, and completed GCSEs including English and Mathematics at Westbridge School in June 2024. Those facts stay the same in both versions.</p>
      <p className="leading-8">Sam&apos;s starting profile is vague: “Hardworking team player looking for a new challenge. Good communication and organisation skills.” The two versions below replace adjectives with evidence.</p>
      <div className="grid gap-4 md:grid-cols-3">{[
        ["Customer enquiries", "Sam answers shop-floor questions, checks stock with colleagues and explains alternatives. This supports customer-facing work, not an invented contact-centre history."],
        ["Accurate information", "Sam checks shelf labels against a price list. In volunteering, Sam maintains an Excel attendee list, checks names and dates, and flags unclear entries to the organiser."],
        ["Team handovers", "Sam passes unresolved enquiries and next steps to the next shift. That demonstrates clear communication, not management responsibility."]
      ].map(([heading,body])=><article key={heading} className="rounded-xl border border-line bg-paper p-5"><h3 className="font-bold text-navy">{heading}</h3><p className="mt-3 leading-7">{body}</p></article>)}</div>
      <p className="leading-8">For your own advert, separate essential requirements from desirable ones. Put a real example beside each requirement. An empty space is a gap to assess, not a prompt to invent something. Check essential licences or qualifications before investing time in the application.</p>
    </div></section>
    {examples.map((example,index)=><section key={example.id} id={example.id} className="scroll-mt-24 border-t border-line bg-surface py-12"><div className="container-page max-w-5xl">
      <h2 className="font-display text-3xl font-semibold text-navy">{index+2}. Tailor the application for {example.role.toLowerCase()}</h2>
      <p className="mt-5 rounded-lg border border-line bg-white p-5 leading-7"><strong>Fictional vacancy: {example.employer}.</strong> {example.advert}</p>
      <div className="mt-6 grid items-start gap-6 lg:grid-cols-2">
        <article className="rounded-xl border border-line bg-white p-6"><h3 className="text-xl font-bold text-navy">CV sections after tailoring</h3><p className="mt-3 font-bold">Sam Taylor • Leeds • [your email and phone]</p><h4 className="mt-5 font-bold">Profile</h4><p className="mt-2 leading-7">{example.profile}</p><h4 className="mt-5 font-bold">Retail Assistant — Westbridge Stores</h4><p className="text-sm text-muted">June 2024–present</p><ul className="mt-3 list-disc space-y-3 pl-5 leading-7">{example.bullets.map(b=><li key={b}>{b}</li>)}</ul><h4 className="mt-5 font-bold">Event volunteer — Westbridge Community Events</h4><p className="text-sm text-muted">January 2025–present</p><p className="mt-2 leading-7">Maintains an Excel attendee list, checks names and dates against registration forms, and flags unclear entries to the organiser. Uses basic sorting and filters to review entries.</p><h4 className="mt-5 font-bold">Education</h4><p className="mt-2 leading-7">Westbridge School — GCSEs including English and Mathematics, June 2024.</p></article>
        <article className="rounded-xl border border-line bg-white p-6"><h3 className="text-xl font-bold text-navy">Matching letter</h3><p className="mt-4 leading-7">Dear Hiring Manager,</p>{example.letter.map(p=><p key={p} className="mt-4 leading-7">{p}</p>)}<p className="mt-4 leading-7">Yours faithfully,<br />Sam Taylor</p></article>
      </div>
      <p className="mt-5 leading-8"><strong>Why these changes fit:</strong> {example.explanation}</p>
    </div></section>)}
    <section className="bg-paper py-12"><div className="container-page max-w-5xl"><h2 className="font-display text-3xl font-semibold text-navy">4. Check gaps and keep the wording honest</h2><p className="mt-5 leading-8">Sam must not claim telephone complaint handling, CRM experience, advanced Excel, staff management or a booking qualification. None is in the evidence bank. If the employer requires a skill Sam lacks, Sam can ask whether related experience is acceptable or choose a more suitable vacancy. A keyword match score does not replace that judgement.</p><p className="mt-4 leading-8">Read your letter beside your CV. Check names, dates, systems and responsibilities. Follow the requested file format, then use the <Link className="font-bold underline" href="/tools/ats-score-checker">free CV readability and advert checker</Link> to look for issues you can actually fix.</p><div className="mt-6"><ButtonLink href="/tools/job-application-pack-uk" trackingLabel="tailoring_guide_pack">Build a CV and letter for your next advert</ButtonLink></div><p className="mt-3 text-sm leading-6 text-muted">The application-pack tool is free. Saving in the editor needs an account; personalised PDF and Word downloads are paid. Fictional examples on this page do not enter your draft.</p></div></section>
    <section id="save-versions" className="scroll-mt-24 border-t border-line bg-white py-12"><div className="container-page max-w-5xl"><h2 className="font-display text-3xl font-semibold text-navy">5. Save a version you can recognise later</h2><p className="mt-5 leading-8">Keep an unchanged master copy. Name each finished file with the role and employer, for example Sam-Taylor-Customer-Service-Northbank.pdf. Record the filename, submission date and follow-up in the <Link href="/tools/job-application-tracker-uk" className="font-bold underline">free job application tracker</Link>. Check the saved advert before an interview.</p><p className="mt-4 leading-8">In WorkCV, open your saved CV and choose “Duplicate for another job” in the editor. Update the duplicate&apos;s profile, relevant bullets and letter, then preview both documents. Duplication copies the starting document; you decide how to adapt it. If you only need one saved pair, you can keep editing that paid pair for {site.price} once.</p><p className="mt-4 leading-8">For separate saved versions, the {site.passPrice} Job Search Pass covers existing CVs and new ones created during {site.passDays} days. Covered documents remain editable and downloadable afterwards; new CVs after expiry need a new purchase. <Link href="/pricing#job-search-pass" className="font-bold underline">Compare one saved CV with the Job Search Pass</Link>.</p><h3 className="mt-8 text-xl font-bold text-navy">Before you send</h3><ul className="mt-4 list-disc space-y-3 pl-5 leading-7"><li>The profile addresses this role, with evidence behind each claim.</li><li>The most relevant bullets come first within each job.</li><li>Employers, dates and qualifications are accurate in both documents.</li><li>The letter names the correct employer and role.</li><li>Missing requirements have not become invented skills.</li><li>The files open correctly and use the employer&apos;s requested format.</li></ul></div></section>
    <TailoringEvidenceBank />
    <PassOffer audience="tailoring" trackingLabel="tailoring_guide_pass" />
    <FaqSection faqs={faqs} title="Questions about tailoring a CV" />
    <section className="bg-paper py-12"><div className="container-page max-w-5xl"><h2 className="text-xl font-bold text-navy">Sources and more examples</h2><p className="mt-4 leading-7">The general method follows <a className="font-bold underline" href="https://nationalcareers.service.gov.uk/careers-advice/cv-sections">National Careers Service CV guidance</a> and <a className="font-bold underline" href="https://jobhelp.campaign.gov.uk/improve-your-chances-of-getting-a-job/cv-job-applications-interviews/make-your-cv-stand-out/tailoring-your-cv/">JobHelp&apos;s tailoring guidance</a>. The worked applications are original WorkCV examples.</p><div className="mt-5 flex flex-wrap gap-5 font-bold underline"><Link href="/cv-template-retail-uk">Retail examples</Link><Link href="/cv-template-warehouse-uk">Warehouse examples</Link><Link href="/cv-template-customer-service-uk">Customer service pack</Link><Link href="/cover-letter-examples-uk">More cover letters</Link></div></div></section>
  </>;
}
