import type { Metadata } from "next";

import { AdviceCard, BulletList, EditorialGuideShell, GuideSection } from "@/components/editorial-guide-shell";

const path = "/common-job-interview-questions-uk";
export const metadata: Metadata = { title: "21 Common Job Interview Questions and Answers UK", description: "Prepare for 21 common UK interview questions with what the employer is testing, answer structures, evidence prompts and mistakes to avoid.", alternates: { canonical: path }, openGraph: { title: "21 Common Job Interview Questions and Answer Plans", description: "Question-by-question guidance for relevant, truthful interview answers.", url: path } };

const questions = [
  ["1. Tell me about yourself", "Can you summarise the relevant thread in your experience?", "Present role or recent experience → two relevant strengths with evidence → why this role is the logical next step.", "Do not retell your life story or read your CV line by line."],
  ["2. Why do you want this role?", "Do you understand the work, and is your motivation credible?", "Name two real responsibilities that attract you and connect each to experience, ability or a considered development goal.", "Avoid answers based only on pay, convenience or generic enthusiasm."],
  ["3. Why do you want to work here?", "Have you researched this employer rather than any employer?", "Use one relevant fact about the organisation, one about the role or team and one reason that matters to your work.", "Do not flatter the brand or recite the About page."],
  ["4. What are your strengths?", "Which useful qualities can you prove?", "Choose two strengths from the person specification and give a short example or result for each.", "Do not give a list of adjectives with no evidence."],
  ["5. What is a weakness you are working on?", "Are you self-aware and able to improve?", "Choose a genuine, non-critical development area; explain its effect, the action you take and the progress you have observed.", "Avoid fake weaknesses such as perfectionism or a weakness that makes the core job unsafe."],
  ["6. Why are you leaving your current job?", "Is the move thoughtful and professionally explained?", "Keep it forward-looking: the scope, development or environment you seek, plus why this vacancy fits.", "Do not criticise individuals or disclose confidential disputes."],
  ["7. Why is there a gap in your CV?", "Can you explain the timeline clearly?", "State the reason briefly, mention relevant activity if any, and move to your readiness and fit now.", "Do not apologise repeatedly or invent courses and responsibilities."],
  ["8. Tell me about a difficult problem you solved", "How do you investigate, decide and act?", "Use STAR. Make your diagnosis and personal actions clearer than the background.", "Do not choose a story where the problem disappears by luck."],
  ["9. Tell me about a time you worked under pressure", "Can you prioritise without losing standards?", "Explain competing demands, how you assessed urgency, who you informed and what you protected.", "Avoid presenting constant crisis as a sign of good planning."],
  ["10. Give an example of teamwork", "How do you contribute with other people?", "Describe the shared goal, your distinct contribution, how you communicated and the team result.", "Do not say only ‘we’; make your contribution visible without taking all the credit."],
  ["11. Tell me about a disagreement at work", "Can you handle conflict constructively?", "Focus on the work issue, how you listened, the evidence or compromise used and the outcome.", "Do not make the other person the villain."],
  ["12. Tell me about a mistake or failure", "Do you take responsibility and learn?", "Choose a real, recoverable example; own your part, explain the correction and show what changed afterwards.", "Do not claim you never fail or choose a disguised success."],
  ["13. Describe a time you improved something", "Can you notice and deliver useful change?", "Explain the original problem, how you involved affected people, what you changed and how you assessed it.", "Do not claim a team-wide improvement without explaining your role."],
  ["14. How do you prioritise your workload?", "Is your method reliable when demands compete?", "Explain your criteria—risk, deadline, dependency and impact—then give a short example and communication step.", "Avoid ‘I just work harder’ as the whole method."],
  ["15. How would you deal with a difficult customer or stakeholder?", "Can you remain calm, understand the issue and act within policy?", "Use a real example if possible: listen, clarify, acknowledge, resolve or escalate, document and follow up.", "Do not promise the customer anything outside your authority."],
  ["16. How do you ensure accuracy or quality?", "Do you have a repeatable method?", "Describe checks, standards, tools or peer review and one time the method prevented or caught an issue.", "Do not simply say you pay attention to detail."],
  ["17. What would you do in your first 30–90 days?", "Can you learn before changing things?", "Structure around learn → relationships → early delivery. Adapt to the seniority and information available.", "Do not promise sweeping change before understanding the organisation."],
  ["18. What achievement are you most proud of?", "What do you value, and can you explain your impact?", "Choose an achievement relevant to the role; explain difficulty, contribution, result and why it mattered.", "Do not choose prestige over relevance."],
  ["19. Where do you see yourself in a few years?", "Does the role fit a plausible direction?", "Discuss skills, responsibility or contribution you want to develop and how this role provides a credible next step.", "Avoid promising a title on a fixed date or implying this role is temporary."],
  ["20. What are your salary expectations?", "Are expectations aligned with the role and market?", "Use the advertised range where available. Otherwise give a researched range, explain flexibility around the total package and ask about budget.", "Do not invent a current salary or give an unresearched number."],
  ["21. Do you have any questions for us?", "Have you thought seriously about the work and decision?", "Ask about success, priorities, team, support and next steps—questions that help you judge the role.", "Do not say no, and do not ask only questions answered in the advert."],
] as const;

const faqs = [
  { question: "What are the most common interview questions in the UK?", answer: "Expect questions about your experience, motivation, strengths, development areas and reasons for applying, plus competency questions tied to the person specification. The advert is a better predictor than any universal list." },
  { question: "Should I memorise answers?", answer: "Memorise the facts, examples and structure—not complete sentences. Listening and adapting to the exact wording is more important than delivering a polished answer to a different question." },
  { question: "How long should an interview answer be?", answer: "Use enough detail to answer clearly, then stop. A motivation answer may take under a minute; a substantial competency example may need two or three. Watch the interviewer and invite a follow-up rather than filling silence." },
  { question: "What if I have no work example?", answer: "Use a truthful example from study, volunteering, caring responsibilities, projects or community activity if the behaviour transfers. Be clear about the context and never present it as employment when it was not." },
];

export default function InterviewQuestionsPage() {
  return <EditorialGuideShell path={path} eyebrow="UK interview question bank" title="21 common job interview questions—with a plan for answering each one." intro="A useful question list should tell you what the interviewer is trying to learn, how to shape relevant evidence and what weakens an answer. Use these plans to prepare; do not memorise them as scripts." answer="Start with the job description: every essential requirement can become a question. Prepare four to six real examples, then use the list below to practise motivation, competency, development and closing questions. Say what you personally did and never invent a number or result." reviewed="13 September 2026" faqs={faqs} ctaHeading="Your interview answers should be supported by the CV they received." ctaBody="Use the vacancy and your evidence to build a focused UK CV. Preview the document free, then pay once only if you choose to download the PDF." trackingContext="interview_questions_editorial" relatedLinks={[["Interview preparation checklist", "/how-to-prepare-for-a-job-interview-uk"], ["Job Application Pack", "/tools/job-application-pack-uk"], ["Thank-you email examples", "/thank-you-email-after-interview-uk"], ["Cover letter generator", "/tools/cover-letter-generator-uk"], ["No-subscription CV builder", "/cv-builder-no-subscription-uk"]]}>
    <GuideSection label="How to use this list" title="Prepare evidence first, wording second."><div className="grid gap-5 md:grid-cols-3"><AdviceCard title="Predict"><p>Highlight the person specification’s behaviours, duties and outcomes. Rewrite each one as “Tell me about a time…” and “How would you…” questions.</p></AdviceCard><AdviceCard title="Select"><p>Choose four to six examples that cover multiple behaviours. One project can show planning, communication and problem solving when each claim is true.</p></AdviceCard><AdviceCard title="Practise"><p>Say answers aloud, vary the question wording and ask a friend to probe: “What did you do?”, “Why?” and “What happened?”</p></AdviceCard></div></GuideSection>
    <GuideSection label="21 questions" title="What they are testing, a useful structure and the trap to avoid." tone="paper"><div className="grid gap-5 lg:grid-cols-2">{questions.map(([question, testing, structure, avoid]) => <AdviceCard key={question} title={question}><p><strong className="text-navy">They are testing:</strong> {testing}</p><p><strong className="text-navy">Build the answer:</strong> {structure}</p><p><strong className="text-navy">Avoid:</strong> {avoid}</p></AdviceCard>)}</div></GuideSection>
    <GuideSection label="Worked STAR example" title="A clear answer shows the decision, not just the happy ending."><div className="grid gap-5 lg:grid-cols-[0.7fr_1.3fr]"><AdviceCard title="Question"><p>“Tell me about a time you had to manage competing priorities.”</p><p><strong className="text-navy">What this tests:</strong> judgement, planning, communication and delivery under pressure.</p></AdviceCard><AdviceCard title="Answer plan"><p><strong className="text-navy">Situation:</strong> Two client reports were due when an urgent data correction affected one deadline.</p><p><strong className="text-navy">Task:</strong> Deliver accurate work without leaving either client uninformed.</p><p><strong className="text-navy">Action:</strong> I checked the impact, separated work that could continue, agreed priority with my manager, told both contacts what to expect and added a second check before release.</p><p><strong className="text-navy">Result:</strong> Both reports were delivered to the agreed revised times, and the added check became part of the next reporting cycle.</p><p className="italic">Only use this structure with your own facts. If your result was qualitative, say so rather than adding a fabricated percentage.</p></AdviceCard></div></GuideSection>
    <GuideSection label="Your six-story bank" title="Fill these evidence slots before practising." tone="paper"><BulletList items={["Problem solved: the issue, your diagnosis, action and result.", "Pressure or priorities: what competed, how you decided and who you informed.", "Teamwork: the shared goal, your contribution and how you worked with others.", "Communication: the audience, difficulty, choice of approach and response.", "Improvement: the original weakness, your proposal, implementation and evidence of change.", "Setback or feedback: your responsibility, correction, learning and changed behaviour."]} /></GuideSection>
    <GuideSection label="Answer quality check" title="Before you call an answer ready, test these six things."><BulletList items={["It answers the question asked, not merely the example you wanted to use.", "The context is brief enough that your decisions remain the focus.", "It distinguishes your contribution from the team’s contribution.", "It connects to a requirement in this vacancy.", "Every number, date, tool, responsibility and outcome is accurate.", "It ends with a result, learning or clear reflection instead of trailing off."]} /><p className="mt-8 text-sm leading-7 text-muted">Research reference: <a className="font-bold text-navy underline" href="https://www.prospects.ac.uk/careers-advice/interview-tips/interview-questions/">Prospects’ interview questions guide</a>, alongside the role-specific method in the <a className="font-bold text-navy underline" href="https://nationalcareers.service.gov.uk/careers-advice/interview-advice">National Careers Service interview advice</a>.</p></GuideSection>
  </EditorialGuideShell>;
}
