import type { Metadata } from "next";
import Link from "next/link";
import { SupportingStatementPlanner } from "@/components/supporting-statement-planner";
import { statementExample, buildStatement } from "@/lib/supporting-statement";
import { site } from "@/lib/site";
import { TrackedLink } from "@/components/tracked-link";
import { analyticsPlacements } from "@/lib/analytics-placements";
export const metadata: Metadata = { title: "Civil Service Supporting Statement Planner UK — Free Evidence Worksheet", description: "Map each Civil Service application criterion to your own actions and outcomes. Free private worksheet, word count, worked example and text download.", alternates: { canonical: "/tools/supporting-statement-planner-uk" } };
export default function Page() {
  return <main className="bg-paper"><div className="container-page space-y-10 py-14">
    <header className="max-w-3xl space-y-5"><p className="text-sm font-bold uppercase text-navy">Free UK application evidence worksheet</p><h1 className="font-display text-4xl font-semibold text-navy md:text-6xl">Build a supporting statement from evidence, not generic claims.</h1><p className="text-lg leading-8">For a Civil Service personal or supporting statement, start with the criteria in the vacancy. Show what you personally did and what happened. This planner helps organise that evidence; it is not a short CV profile generator and cannot score your application.</p><p className="text-sm text-muted">Reviewed 24 September 2026 · WorkCV editorial team · No affiliation with the Civil Service.</p></header>
    <SupportingStatementPlanner />
    <section className="max-w-4xl space-y-5" id="worked-example"><h2 className="text-3xl font-bold text-navy">A complete fictional example</h2><p className="leading-7">Criterion: <strong>{statementExample.criterion}</strong>. This example uses community volunteering, not invented paid experience or a fabricated percentage improvement. Replace it with your own facts.</p><blockquote className="border-l-4 border-gold bg-white p-6 leading-8">{buildStatement([statementExample])}</blockquote><p className="leading-7">Why it helps: the context is concrete, the actions are attributable to the applicant, and the outcome is modest and checkable. What it cannot prove: that this example meets the grade, scope or depth of your particular vacancy. Add the responsibility, decisions and learning your advert actually asks for.</p></section>
    <section className="max-w-4xl space-y-5"><h2 className="text-3xl font-bold">How to use the worksheet well</h2><ol className="list-decimal space-y-3 pl-6 leading-8"><li>Copy each assessed criterion from the advert. Separate essential and desirable requirements; do not assume every Success Profile element is assessed.</li><li>Choose a real example. Work, study or volunteering may supply evidence, depending on the criterion. State your own contribution, not just what the team did.</li><li>Explain the situation briefly, spend most space on your actions, and describe the outcome honestly. Numbers are optional; do not invent them.</li><li>Read the assembled draft. Remove repetition, add necessary context and prioritise essential criteria within the vacancy's limit.</li><li>Follow name-blind, confidentiality and AI-use instructions. Check the actual application field before submitting.</li></ol></section>
    <section className="max-w-4xl space-y-4"><h2 className="text-3xl font-bold">Sources and limits</h2><p className="leading-8">The <a className="underline" href="https://www.civil-service-careers.gov.uk/how-to-write-your-ps/">Civil Service personal statement guidance</a> explains relevance, evidence and word limits. The <a className="underline" href="https://www.gov.uk/government/publications/success-profiles">official Success Profiles framework</a> explains the different assessment elements. The vacancy remains the authority for what you must submit.</p><p className="leading-8">This first version is designed around Civil Service statements, not NHS-specific supporting information or an employer assessment rubric. Status labels describe whether you entered the worksheet fields, not whether an employer will accept your evidence.</p></section>
    <aside className="rounded-lg border border-line bg-white p-6"><h2 className="text-2xl font-bold">Also asked to submit a CV?</h2><p className="mt-3 leading-7">Keep the statement as a free text document. If the vacancy also accepts a CV attachment, <TrackedLink placement={analyticsPlacements.statementPlannerTemplates} className="font-bold underline" href="/templates">choose a CV layout</TrackedLink> or <Link className="font-bold underline" href="/tools/job-application-pack-uk">review your CV against the advert</Link>. WorkCV's editor requires login; building and previewing are free, then {site.price} once unlocks that saved CV's PDF. <Link className="underline" href="/pricing">Full pricing</Link>. Do not buy a PDF if the application only asks for form text.</p></aside>
  </div></main>;
}
