import Link from "next/link";
import { Guide, GuideSection, GuideTable, CvTextExample, GuideSource, guideMetadata } from "@/components/cv-guide";
import { CareerTimelineWorksheet } from "@/components/career-worksheets";
import { FaqSection } from "@/components/marketing";
import { PassOffer } from "@/components/pass-offer";
import { jobPassExamples as ex } from "@/lib/job-pass-examples";
const path="/cv-after-long-service-uk";
export const metadata=guideMetadata(path,"CV After Years at One Company: UK Examples & Worksheet","See complete UK CV examples for long service with one employer, including promotions and an unchanged title. Build a truthful career timeline with a free worksheet.");
const faqs=[
{question:"How do I write a CV after 20 years with one employer?",answer:"Start with your actual roles and dates, then choose recent evidence relevant to the vacancy. Show changes in responsibilities, systems or work even if the employer stayed the same. Long service does not require a twenty-year list of repeated duties."},
{question:"Do I list every promotion?",answer:"Keep the titles and dates that explain your progression. Give relevant recent roles more detail, and summarise earlier work. Where an application form asks for a full history, provide it accurately."},
{question:"What if my title never changed?",answer:"Keep the one truthful title and show how your work changed within it: new systems, different enquiries, process updates or training colleagues. Do not invent a promotion to make the history appear stronger."},
{question:"Should I repeat the company name for each role?",answer:"You can. Separate entries make each title and date range explicit and fit WorkCV's editor. A grouped employer heading can work in a manually formatted CV, but keep the dates of each role clear."},
{question:"What if I left and returned?",answer:"Show the two separate periods, with any intervening employment in chronological order. Do not describe the employer as one continuous period that includes years spent elsewhere."},
{question:"How much earlier experience should I include?",answer:"Keep what explains your history and supports the job. Summarise older, less relevant duties rather than apply a universal ten-year cut-off. Follow the employer's instructions, especially for forms that request full history."},
{question:"What if I cannot remember the months?",answer:"Check your records when possible. Use year-only dates consistently if that is the precision you can support. Do not invent January or December dates to fill a form."},
{question:"Must I explain why I left?",answer:"A CV does not need a reason beside every job. If the employer asks, answer accurately. Do not invent redundancy or a personal circumstance to explain a missing detail."},
{question:"Can I use one CV for different jobs?",answer:"You can reuse a factual starting CV and tailor its emphasis. Keep titles, dates and qualifications consistent while adapting your profile, evidence order and letter. Separate saved versions help you retain what you sent."}];
export default function Page(){return <Guide path={path} title="How to write a CV after years at the same company" intro="Keep your employer, job titles and dates accurate. Show the responsibilities and evidence that matter for your next job, whether you changed roles or kept the same title. These complete UK examples and a free career timeline worksheet show how." reviewed="2026-10-05" published="2026-10-05" placement="long_service_guide" action={["Start my own CV","/editor?template=classic&new=1"]} links={[["Tailor one CV to two vacancies","/tailor-cv-to-job-description-uk"],["Shorten a long CV","/shorten-cv-to-two-pages"],["Applying for a less senior role","/overqualified-cv-example-uk"],["CV after redundancy","/situations/made-redundant"]]}>
 <nav aria-label="On this page" className="flex flex-wrap gap-4 text-sm font-bold underline"><a href="#complete-example">Complete CV and letter</a><a href="#unchanged-title">One unchanged title</a><a href="#timeline">Build your timeline</a><a href="#questions">Questions</a></nav>
 <GuideSection id="complete-example" title="A complete CV after 20 years with one employer">
 <p>Sam Taylor worked at fictional Northbridge Office Supplies from 2006 to 2026. Three genuine roles show progression. The new application emphasises records, customer enquiries and coordination. All people, employers and vacancies in these examples are fictional.</p>
 <CvTextExample title="The office administrator vacancy" text={ex.longAdvert}/><CvTextExample title="Sam's complete CV" text={ex.longCv}/><CvTextExample title="Sam's matching cover letter" text={ex.longLetter}/>
 <GuideTable caption="What the vacancy asks for and what Sam can support" headings={["Requirement","Evidence","Decision"]} rows={[["Accurate records","Order records and dispatch checks","Lead with specific checks, not a vague attention-to-detail claim."],["Shared inbox","Coordinated customer enquiries","Include in the profile and recent role."],["Basic Excel","Filters and basic formulas","Keep that level; do not claim advanced Excel."],["Arrange appointments","Delivery coordination","Related experience, not direct appointment-booking evidence."],["Technical services","No sector experience supplied","Do not invent it; this advert calls it desirable."]]}/>
 <p>Sam's earlier roles remain visible with less space. The CV does not claim payroll knowledge, line management or a percentage improvement. “Reduced errors by 30%” would be unsupported. Plain evidence of what Sam checked is more useful than an invented metric.</p>
 <GuideSource href="https://nationalcareers.service.gov.uk/careers-advice/cv-sections">National Careers Service: CV sections and relevant work history</GuideSource>
 </GuideSection>
 <GuideSection id="unchanged-title" title="What if you had the same title for years?"><p>Priya Shah's title stayed Customer Service Assistant from 2009 to 2026. The work expanded from telephone queries into email support, customer records and process guidance. Months are unknown, so the example keeps year-only dates.</p><CvTextExample title="Priya's complete CV for a customer support role" text={ex.sameCv}/><p>One role is enough. A newer system, a changed process or a different kind of enquiry can show development without inventing promotions. No measured outcome is required where none is known.</p></GuideSection>
 <GuideSection title="Choose a format that preserves your real history"><GuideTable caption="Different long-service histories" headings={["Situation","How to show it","Example"]} rows={[
 ["Different jobs at one employer","Separate dated roles with distinct evidence; repeat the employer if useful.","Senior Administrator, 2018–2026; Administrator, 2012–2018."],
 ["Similar successive roles","List actual titles and dates, reducing repeated duties.","Administrator, 2018–2026; Administrative Assistant, 2012–2018."],
 ["One unchanged title","One employment entry; show changes in the bullets.","Customer Service Assistant, 2009–2026; introduced to email support later."],
 ["Left and returned","Separate periods, with intervening work retained.","Employer A 2021–2026; B 2018–2021; A 2012–2018."],
 ["Concurrent work","Keep overlapping dates if accurate; explain part-time work if true.","Two genuine roles held during the same year."],
 ["Employer renamed","Add the former name if the relationship is accurate.","Riverside Services (formerly Brook Services)."],
 ["Temporary higher duties","Keep the actual title and describe the temporary scope.","Administrator; covered rota coordination during the manager's absence."]
 ]}/><p>Summarise older, less relevant duties thoughtfully. There is no universal rule to delete all work older than ten years. Specialist or academic applications may need a different length; see <Link className="underline" href="/how-long-should-a-cv-be-uk">UK CV length guidance</Link>.</p><GuideSource href="https://cvknowhow.co.uk/career-advice/how-to-format-your-resume-for-multiple-jobs-at-one-company">CV Knowhow: examples for multiple roles with one employer</GuideSource></GuideSection>
 <GuideSection id="timeline" title="Build your career timeline"><p>Use your records and your own recollection. Translate internal abbreviations into plain language; do not upload confidential employer records. The worksheet copies your selected facts into an outline, without generating achievements.</p><CareerTimelineWorksheet/></GuideSection>
 <GuideSection title="Use the same history for a different vacancy"><p>A fictional Customer Service Coordinator vacancy at Elmfield Supplies prioritises order enquiries, delivery updates and clear case notes. Sam can adapt the same facts without changing employment history.</p><CvTextExample title="A second profile from the same evidence" text="Customer-focused administration professional experienced in order enquiries, delivery coordination and accurate records. Used to working with warehouse colleagues and shared inboxes to keep enquiries moving. Seeking a customer service coordination role using clear communication and practical follow-through."/><GuideTable caption="Office administration versus customer service coordination" headings={["Part","Willow office administrator","Elmfield customer service coordinator"]} rows={[["Lead evidence","Records, Excel and detail checks","Inbox coordination and delivery queries"],["Skills order","Record maintenance, Excel, handovers","Enquiry follow-up, delivery coordination, records"],["Letter emphasis","Office records and internal coordination","Keeping customers informed with warehouse input"],["What stays fixed","Employers, dates, actual titles, qualifications","The same facts; no invented ticketing-platform experience"],["Example filename","Sam-Taylor-Willow-CV.pdf","Sam-Taylor-Elmfield-CV.pdf"]]}/><CvTextExample title="Letter paragraph for the second application" text="At Northbridge Office Supplies, I coordinated the shared customer inbox and followed up dispatch differences with warehouse colleagues. Earlier in my time with the business, I answered delivery queries and arranged deliveries. This experience is relevant to keeping your customers informed while maintaining accurate records."/><p>Use the <Link className="font-bold underline" href="/tools/job-application-pack-uk">CV and cover-letter tailoring tool</Link> when you have a vacancy and evidence, then record filenames and the next action in the <Link className="underline" href="/tools/job-application-tracker-uk">application tracker</Link>.</p></GuideSection>
 <PassOffer audience="tailoring" trackingLabel="long_service_pass_example"/>
 <div id="questions"><FaqSection faqs={faqs} title="Questions about a CV after long service"/></div>
 </Guide>;}
