import type { Metadata } from "next";
import Link from "next/link";
import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { site } from "@/lib/site";
import { TrackedLink } from "@/components/tracked-link";
import { analyticsPlacements } from "@/lib/analytics-placements";
export const metadata: Metadata = { title: "UK CV Layout Tests — Sample PDFs and Reading Order", description: "Compare six WorkCV layouts with the same fictional CV. Download sample PDFs, inspect extracted text and understand the limits of parsing tests.", alternates: { canonical: "/cv-layout-tests-uk" } };
type Report = { generatedAt: string; parser: string; renderer: string; reports: Array<{ id: string; name: string; template: string; preset: string; pages: number; words: number; headings: string[] }> };
export default function Page() {
  const file = join(process.cwd(), "public/samples/layouts/report.json");
  const report: Report | null = existsSync(file) ? JSON.parse(readFileSync(file, "utf8")) : null;
  return <main className="bg-paper"><div className="container-page space-y-10 py-14">
    <header className="max-w-4xl space-y-5"><p className="text-sm font-bold uppercase text-navy">Original WorkCV product tests</p><h1 className="font-display text-4xl font-semibold text-navy md:text-6xl">What can a text extractor read from our CV layouts?</h1><p className="text-lg leading-8">Compare the same fictional CV in six layouts, download the actual PDF, and inspect its extracted reading order. This demonstrates one parser's output. It is not a certification by an employer or a universal ATS pass.</p></header>
    <section className="max-w-4xl space-y-4"><h2 className="text-3xl font-bold">Choose by your application, not a score</h2><ul className="list-disc space-y-3 pl-6 leading-7"><li><strong>Classic:</strong> a straightforward single-column starting point.</li><li><strong>Education first:</strong> put study and projects ahead of employment when they provide your strongest evidence.</li><li><strong>Compact single column:</strong> tighter spacing without a sidebar. It does not promise one page for every CV.</li><li><strong>Experienced professional:</strong> a single-column preset for work history, projects and qualifications. Reorder sections to match your evidence; two pages are not a hard requirement.</li><li><strong>Modern and Compact:</strong> sidebar designs. Compare their extracted sequence carefully, especially skills and contact details. Use a single column if the vacancy requests one.</li></ul></section>
    {report ? <section className="space-y-6" id="results"><h2 className="text-3xl font-bold">Reproducible sample results</h2><p className="text-sm leading-7">Generated {report.generatedAt.slice(0, 10)} with {report.renderer}; extraction by {report.parser}. Same fictional content, A4, browser print rendering. Counts belong to these sample files, not your CV.</p><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{report.reports.map((item) => <article key={item.id} className="min-w-0 space-y-4 rounded-lg border border-line bg-white p-5"><h3 className="text-xl font-bold">{item.name}</h3><img src={`/samples/layouts/${item.id}.png`} alt={`First page of the fictional ${item.name} sample`} width={595} height={842} className="w-full border border-line" /><p className="text-sm">{item.pages} pages · {item.words} extracted words</p><p className="break-words text-xs leading-6">Extracted heading sequence: {item.headings.join(" → ")}</p><p className="flex flex-wrap gap-4 text-sm font-bold"><a className="underline" href={`/samples/layouts/${item.id}.pdf`}>Sample PDF</a><a className="underline" href={`/samples/layouts/${item.id}.txt`}>Full extracted text</a></p><TrackedLink placement={analyticsPlacements.layoutEvidenceEditor} className="inline-flex min-h-11 items-center rounded bg-navy px-4 text-sm font-bold text-white" href={`/editor?new=1&template=${item.template}&layoutPreset=${item.preset}`}>Use this layout</TrackedLink></article>)}</div></section> : <p>Sample evidence is being prepared. No test result is claimed until the files are available.</p>}
    <section className="max-w-4xl space-y-4" id="methodology"><h2 className="text-3xl font-bold">Method, limitations and how to repeat the check</h2><ol className="list-decimal space-y-3 pl-6 leading-8"><li>We render the same fictional candidate content through WorkCV's PDF document component, changing only the design or preset.</li><li>We extract text page by page using PDF.js, retaining the parser's item order. We record page count, whitespace-delimited word count and heading sequence, and assert selected names, employers and optional-section text are present.</li><li>We render the resulting PDFs for visual review. Passing selected phrase checks alone does not establish that every character survived or that the reading order is ideal.</li><li>Download a sample, open its text file and compare both. Then <Link className="underline" href="/tools/cv-format-checker-uk">check your own PDF or DOCX privately</Link>. A different parser, export setting or document may produce different results.</li></ol><p className="leading-8">PDF.js is a general-purpose PDF reader, not Workday, Greenhouse or another employer's screening system. We have not tested these files in those systems. Heading order is an observation, not a hiring prediction. Sample certificates and work histories are fictional and must not be copied as personal claims.</p><p className="leading-8">Technical references: <a className="underline" href="https://mozilla.github.io/pdf.js/examples/">PDF.js document, text and rendering examples</a>. <a className="underline" href="/samples/layouts/report.json">Download the machine-readable test record</a>.</p></section>
    <aside className="rounded border border-line bg-white p-6"><h2 className="text-2xl font-bold">Try your own content before paying</h2><p className="mt-3 leading-8">Sample PDFs are free. The editor requires login and lets you build and preview your own CV. {site.price} once unlocks the PDF for that saved CV, including its later edits and re-downloads. A separate saved CV has a separate purchase. <Link href="/pricing" className="underline">Pricing details</Link> · <Link href="/templates" className="underline">Template gallery</Link>.</p></aside>
  </div></main>;
}
